/**
 * P1-4: Shot Library — 55 Structured Shot Presets
 *
 * Covers 6 categories × 8-10 presets each, mapped to CinematicParamPanel.
 * All prompts are English for downstream AI image/video generation.
 */
import type { ShotPreset } from "./types.ts"

export const SHOT_PRESETS: ShotPreset[] = [
  // ========================================================================
  // ESTABLISHING — 建立环境
  // ========================================================================
  {
    id: "establish-extreme-wide",
    name: "极远景",
    nameEn: "Extreme Wide",
    category: "establishing",
    shotSize: "extreme wide shot",
    cameraAngle: "eye level",
    cameraMovement: "static",
    lens: "14mm",
    composition: "rule of thirds",
    mood: "grand, vast",
    useCases: ["场景建立", "宏大叙事", "自然风光"],
    prompt: "extreme wide establishing shot, vast landscape, tiny figures for scale, epic cinematic atmosphere, 14mm ultra-wide lens, deep focus everything in focus",
    cinematicParams: { shotScale: 0.95, cameraMotion: 0.05, lighting: 0.5, tone: 0.6, depthOfField: 0.1, aspectRatio: 0.9 },
  },
  {
    id: "establish-aerial",
    name: "航拍俯瞰",
    nameEn: "Aerial Top-Down",
    category: "establishing",
    shotSize: "extreme wide shot",
    cameraAngle: "top-down / bird's eye",
    cameraMovement: "slow pan",
    lens: "24mm",
    composition: "geometric patterns",
    mood: "revealing, majestic",
    useCases: ["城市开场", "场景揭示", "地图感转场"],
    prompt: "bird's eye aerial shot, top-down view, geometric urban patterns, slow drone pan, 24mm wide lens, crisp sharp detail, aerial cinematography",
    cinematicParams: { shotScale: 1.0, cameraMotion: 0.15, lighting: 0.5, tone: 0.55, depthOfField: 0.05, aspectRatio: 0.85 },
  },
  {
    id: "establish-city-skyline",
    name: "城市天际线",
    nameEn: "City Skyline",
    category: "establishing",
    shotSize: "long shot / wide",
    cameraAngle: "slightly low angle",
    cameraMovement: "slow crane up",
    lens: "35mm",
    composition: "horizon at lower third",
    mood: "urban, aspirational",
    useCases: ["城市开场", "商业题材", "傍晚/夜景"],
    prompt: "city skyline establishing shot, dramatic sunset or twilight, slow crane-up reveal, 35mm lens, golden hour rim light on buildings, cinematic wide",
    cinematicParams: { shotScale: 0.85, cameraMotion: 0.2, lighting: 0.6, tone: 0.7, depthOfField: 0.15, aspectRatio: 0.9 },
  },
  {
    id: "establish-interior-wide",
    name: "室内全景",
    nameEn: "Interior Wide",
    category: "establishing",
    shotSize: "wide shot",
    cameraAngle: "eye level",
    cameraMovement: "slow dolly",
    lens: "24mm",
    composition: "deep space, layers of depth",
    mood: "spacious, inviting",
    useCases: ["室内场景建立", "豪宅/办公室", "空间展示"],
    prompt: "wide interior establishing shot, elegant architecture, natural window light, slow dolly movement, 24mm lens, deep space composition, warm ambient lighting",
    cinematicParams: { shotScale: 0.8, cameraMotion: 0.1, lighting: 0.35, tone: 0.65, depthOfField: 0.1, aspectRatio: 0.8 },
  },
  {
    id: "establish-night-city",
    name: "夜景城市",
    nameEn: "Night Cityscape",
    category: "establishing",
    shotSize: "long shot",
    cameraAngle: "high angle",
    cameraMovement: "static or slow tilt",
    lens: "50mm",
    composition: "leading lines (roads/lights)",
    mood: "moody, mysterious",
    useCases: ["悬疑开场", "都市夜戏", "霓虹氛围"],
    prompt: "night city establishing shot, neon reflections on wet streets, foggy atmosphere, static tripod shot, 50mm lens, cinematic teal-orange grade, low-key lighting",
    cinematicParams: { shotScale: 0.8, cameraMotion: 0.05, lighting: 0.75, tone: 0.3, depthOfField: 0.1, aspectRatio: 0.9 },
  },
  {
    id: "establish-desert",
    name: "沙漠史诗",
    nameEn: "Desert Epic",
    category: "establishing",
    shotSize: "extreme wide shot",
    cameraAngle: "low angle against sun",
    cameraMovement: "slow pan",
    lens: "anamorphic 40mm",
    composition: "silhouette at golden hour",
    mood: "epic, harsh, beautiful",
    useCases: ["史诗开场", "冒险题材", "废土风格"],
    prompt: "epic desert establishing shot, dune landscape, golden hour backlight, small figures against massive scale, anamorphic lens, heat haze, IMAX aesthetic",
    cinematicParams: { shotScale: 1.0, cameraMotion: 0.1, lighting: 0.8, tone: 0.8, depthOfField: 0.2, aspectRatio: 0.95 },
  },
  {
    id: "establish-forest",
    name: "森林幽深",
    nameEn: "Deep Forest",
    category: "establishing",
    shotSize: "wide shot",
    cameraAngle: "low angle up through canopy",
    cameraMovement: "slow tilt up",
    lens: "16mm",
    composition: "vertical lines (tree trunks)",
    mood: "mysterious, tranquil",
    useCases: ["奇幻开场", "恐怖氛围", "自然纪录"],
    prompt: "deep forest establishing shot, sunlight filtering through canopy, misty atmosphere, slow tilt-up reveal, 16mm wide angle, volumetric light rays, ethereal mood",
    cinematicParams: { shotScale: 0.75, cameraMotion: 0.15, lighting: 0.4, tone: 0.45, depthOfField: 0.3, aspectRatio: 0.85 },
  },
  {
    id: "establish-ocean",
    name: "海天一色",
    nameEn: "Ocean Horizon",
    category: "establishing",
    shotSize: "extreme wide shot",
    cameraAngle: "eye level at water",
    cameraMovement: "static",
    lens: "35mm",
    composition: "horizon centered",
    mood: "peaceful, infinite",
    useCases: ["文艺片开场", "度假场景", "冥想氛围"],
    prompt: "ocean horizon establishing shot, calm sea meeting sky, golden or blue hour, static composition, 35mm lens, minimalist aesthetic, infinite horizon line",
    cinematicParams: { shotScale: 1.0, cameraMotion: 0.0, lighting: 0.4, tone: 0.5, depthOfField: 0.1, aspectRatio: 0.9 },
  },
  {
    id: "establish-corridor",
    name: "长廊纵深",
    nameEn: "Corridor Depth",
    category: "establishing",
    shotSize: "medium wide",
    cameraAngle: "eye level centered",
    cameraMovement: "slow dolly forward",
    lens: "35mm",
    composition: "one-point perspective",
    mood: "ominous, formal",
    useCases: ["恐怖片开场", "机构/医院", "对称美学"],
    prompt: "corridor establishing shot, one-point perspective, symmetrical architecture, slow dolly forward, clinical lighting, 35mm lens, Kubrick framing, foreboding atmosphere",
    cinematicParams: { shotScale: 0.7, cameraMotion: 0.15, lighting: 0.6, tone: 0.3, depthOfField: 0.25, aspectRatio: 0.8 },
  },

  // ========================================================================
  // CHARACTER — 人物情绪
  // ========================================================================
  {
    id: "char-extreme-cu-eyes",
    name: "眼神特写",
    nameEn: "Extreme CU Eyes",
    category: "character",
    shotSize: "extreme close-up",
    cameraAngle: "eye level",
    cameraMovement: "static",
    lens: "85mm",
    composition: "centered, eyes at rule of thirds upper",
    mood: "intense, intimate",
    useCases: ["情感高潮", "人物揭示", "对视镜头"],
    prompt: "extreme close-up of eyes, shallow depth of field, catchlight reflection, intense emotional gaze, 85mm f/1.4, cinema-quality skin texture, subtle tear detail",
    cinematicParams: { shotScale: 0.0, cameraMotion: 0.0, lighting: 0.45, tone: 0.5, depthOfField: 1.0, aspectRatio: 0.7 },
  },
  {
    id: "char-over-shoulder",
    name: "过肩镜头",
    nameEn: "Over-the-Shoulder",
    category: "character",
    shotSize: "close-up / medium close-up",
    cameraAngle: "eye level",
    cameraMovement: "static",
    lens: "50mm",
    composition: "OTS with rack focus to subject",
    mood: "conversational, natural",
    useCases: ["对话场景", "揭示反应", "双人戏"],
    prompt: "over-the-shoulder shot, soft focus on foreground shoulder, sharp focus on subject face, natural conversation lighting, 50mm lens, intimate framing, cinematic depth of field",
    cinematicParams: { shotScale: 0.15, cameraMotion: 0.0, lighting: 0.4, tone: 0.55, depthOfField: 0.8, aspectRatio: 0.8 },
  },
  {
    id: "char-profile",
    name: "侧脸凝视",
    nameEn: "Profile Gaze",
    category: "character",
    shotSize: "medium close-up",
    cameraAngle: "eye level, profile",
    cameraMovement: "static",
    lens: "85mm",
    composition: "negative space in gaze direction",
    mood: "contemplative, elegant",
    useCases: ["内心独白", "角色登场", "结尾定格"],
    prompt: "profile shot, subject looking into distance, strong rim light separating from dark background, 85mm lens, elegant composition with negative space, contemplative mood",
    cinematicParams: { shotScale: 0.12, cameraMotion: 0.0, lighting: 0.7, tone: 0.4, depthOfField: 0.9, aspectRatio: 0.75 },
  },
  {
    id: "char-dutch-angle",
    name: "斜角紧张",
    nameEn: "Dutch Angle",
    category: "character",
    shotSize: "medium shot",
    cameraAngle: "dutch angle / canted 30°",
    cameraMovement: "slight handheld float",
    lens: "35mm",
    composition: "tilted, unsettling",
    mood: "disoriented, tense, paranoid",
    useCases: ["心理悬疑", "人物崩溃", "噩梦场景"],
    prompt: "dutch angle canted shot, disorienting tilt, unsettling atmosphere, slight handheld float, 35mm lens, harsh shadows, psychological thriller aesthetic, paranoid tension",
    cinematicParams: { shotScale: 0.4, cameraMotion: 0.5, lighting: 0.8, tone: 0.3, depthOfField: 0.4, aspectRatio: 0.8 },
  },
  {
    id: "char-close-shoulder",
    name: "近景侧重",
    nameEn: "Close Shoulder",
    category: "character",
    shotSize: "close-up",
    cameraAngle: "slightly above eye level",
    cameraMovement: "subtle dolly",
    lens: "85mm",
    composition: "centered, intimate",
    mood: "vulnerable, emotional",
    useCases: ["情感流露", "关键对话", "独白时刻"],
    prompt: "close-up shot, head and shoulders, slightly above eye level, subtle dolly movement, 85mm portrait lens, soft diffused key light, cinema-quality facial detail, emotional vulnerability",
    cinematicParams: { shotScale: 0.08, cameraMotion: 0.1, lighting: 0.35, tone: 0.6, depthOfField: 0.85, aspectRatio: 0.7 },
  },
  {
    id: "char-low-angle-hero",
    name: "低角英雄",
    nameEn: "Low Angle Hero",
    category: "character",
    shotSize: "medium shot",
    cameraAngle: "low angle / worm's eye",
    cameraMovement: "slow push-in",
    lens: "24mm",
    composition: "subject fills frame, sky/building behind",
    mood: "powerful, heroic, dominant",
    useCases: ["英雄登场", "权力展示", "对决开场"],
    prompt: "low angle heroic shot, subject towering over camera, sky or grand architecture behind, slow push-in, 24mm wide perspective, dramatic backlighting, powerful presence",
    cinematicParams: { shotScale: 0.45, cameraMotion: 0.2, lighting: 0.65, tone: 0.55, depthOfField: 0.35, aspectRatio: 0.85 },
  },
  {
    id: "char-back-figure",
    name: "背影留白",
    nameEn: "Back Figure",
    category: "character",
    shotSize: "full body / medium full",
    cameraAngle: "eye level from behind",
    cameraMovement: "static",
    lens: "50mm",
    composition: "centered subject, vast space ahead",
    mood: "lonely, mysterious, reflective",
    useCases: ["结尾镜头", "离去场景", "孤独感"],
    prompt: "back view of solitary figure, facing vast landscape or empty space, static composition, 50mm lens, subject centered with negative space, melancholic atmosphere, golden or blue hour lighting",
    cinematicParams: { shotScale: 0.6, cameraMotion: 0.0, lighting: 0.45, tone: 0.35, depthOfField: 0.2, aspectRatio: 0.85 },
  },
  {
    id: "char-rack-focus",
    name: "焦点转换",
    nameEn: "Rack Focus",
    category: "character",
    shotSize: "close-up to close-up",
    cameraAngle: "eye level",
    cameraMovement: "static",
    lens: "85mm",
    composition: "two subjects at different depths",
    mood: "revealing, dramatic",
    useCases: ["揭示信息", "情感转换", "反应镜头"],
    prompt: "rack focus shot, focus pulls from foreground to background subject, 85mm f/1.4, extreme shallow depth of field, dramatic revelation, cinema bokeh, sharp focus transition",
    cinematicParams: { shotScale: 0.1, cameraMotion: 0.0, lighting: 0.5, tone: 0.5, depthOfField: 1.0, aspectRatio: 0.8 },
  },
  {
    id: "char-window-light",
    name: "窗光人像",
    nameEn: "Window Light Portrait",
    category: "character",
    shotSize: "medium close-up",
    cameraAngle: "eye level, 3/4 angle",
    cameraMovement: "static",
    lens: "50mm",
    composition: "window light as key, subject in frame edge",
    mood: "natural, introspective",
    useCases: ["安静对话", "回忆场景", "日常感"],
    prompt: "window light portrait, natural daylight through window as key light, soft shadows, 50mm lens, subject at frame edge looking out, introspective mood, Rembrandt lighting pattern, warm natural tones",
    cinematicParams: { shotScale: 0.2, cameraMotion: 0.0, lighting: 0.3, tone: 0.7, depthOfField: 0.7, aspectRatio: 0.7 },
  },
  {
    id: "char-silhouette",
    name: "剪影轮廓",
    nameEn: "Silhouette Portrait",
    category: "character",
    shotSize: "medium shot",
    cameraAngle: "eye level",
    cameraMovement: "static",
    lens: "50mm",
    composition: "subject against bright background",
    mood: "mysterious, iconic, dramatic",
    useCases: ["秘密对话", "角色登场", "结尾升华"],
    prompt: "silhouette shot, subject as dark shape against bright window or sky, rim light outlining figure, 50mm lens, high contrast, mysterious atmosphere, iconic composition",
    cinematicParams: { shotScale: 0.45, cameraMotion: 0.0, lighting: 0.9, tone: 0.4, depthOfField: 0.25, aspectRatio: 0.8 },
  },

  // ========================================================================
  // ACTION — 动作叙事
  // ========================================================================
  {
    id: "action-tracking-side",
    name: "侧面跟拍",
    nameEn: "Side Tracking",
    category: "action",
    shotSize: "medium shot",
    cameraAngle: "eye level, 90° to subject",
    cameraMovement: "tracking / dolly",
    lens: "35mm",
    composition: "subject at rule of thirds",
    mood: "dynamic, immersive",
    useCases: ["行走", "奔跑", "追逐"],
    prompt: "side tracking shot, subject in motion parallel to camera, smooth dolly movement, 35mm lens, dynamic motion blur on background, immersive action, kinetic energy",
    cinematicParams: { shotScale: 0.45, cameraMotion: 0.55, lighting: 0.5, tone: 0.55, depthOfField: 0.35, aspectRatio: 0.8 },
  },
  {
    id: "action-handheld-chase",
    name: "手持追逐",
    nameEn: "Handheld Chase",
    category: "action",
    shotSize: "medium / medium close-up",
    cameraAngle: "eye level, unstable",
    cameraMovement: "handheld / shaky",
    lens: "28mm",
    composition: "chaotic, immersive POV",
    mood: "urgent, chaotic, visceral",
    useCases: ["追逐场景", "战斗场面", "紧急时刻"],
    prompt: "handheld chase shot, energetic camera shake, subject running in frame, 28mm lens, raw documentary realism, motion blur, dirt and debris, visceral urgency, naturalistic lighting",
    cinematicParams: { shotScale: 0.4, cameraMotion: 0.9, lighting: 0.55, tone: 0.5, depthOfField: 0.3, aspectRatio: 0.8 },
  },
  {
    id: "action-push-in-drama",
    name: "戏剧推近",
    nameEn: "Dramatic Push-In",
    category: "action",
    shotSize: "medium → close-up",
    cameraAngle: "eye level",
    cameraMovement: "slow push-in / dolly zoom",
    lens: "50mm, zooming to 85mm",
    composition: "centered subject",
    mood: "tense, dawning realization",
    useCases: ["关键揭示", "悬念建立", "情感爆发前"],
    prompt: "slow dramatic push-in, dolly zoom effect, subject's expression changing, 50mm to 85mm focal length, Hitchcock vertigo effect, shallow depth of field, growing tension",
    cinematicParams: { shotScale: 0.1, cameraMotion: 0.25, lighting: 0.5, tone: 0.4, depthOfField: 0.8, aspectRatio: 0.8 },
  },
  {
    id: "action-whip-pan",
    name: "快速甩镜",
    nameEn: "Whip Pan",
    category: "action",
    shotSize: "various",
    cameraAngle: "eye level",
    cameraMovement: "fast pan / whip",
    lens: "35mm",
    composition: "motion blur transition",
    mood: "energetic, transitional",
    useCases: ["场景切换", "节奏加快", "动作高潮"],
    prompt: "fast whip pan shot, dramatic motion blur, rapid camera swing, 35mm lens, energetic transition, cinematic speed, dynamic storytelling, action film energy",
    cinematicParams: { shotScale: 0.5, cameraMotion: 0.95, lighting: 0.5, tone: 0.55, depthOfField: 0.3, aspectRatio: 0.8 },
  },
  {
    id: "action-crane-boom",
    name: "摇臂升降",
    nameEn: "Crane Boom",
    category: "action",
    shotSize: "wide → medium (ascending)",
    cameraAngle: "low → eye level",
    cameraMovement: "crane / jib up",
    lens: "24mm",
    composition: "revealing upward",
    mood: "grand, revealing",
    useCases: ["战斗收场", "场景揭示", "壮观收尾"],
    prompt: "crane boom-up shot, revealing scale of scene, smooth mechanical movement, 24mm wide lens, aerial reveal, grand cinematic moment, dust and atmosphere in light",
    cinematicParams: { shotScale: 0.85, cameraMotion: 0.3, lighting: 0.55, tone: 0.6, depthOfField: 0.2, aspectRatio: 0.9 },
  },
  {
    id: "action-circle-orbit",
    name: "环绕运镜",
    nameEn: "Circle Orbit",
    category: "action",
    shotSize: "medium / medium close-up",
    cameraAngle: "eye level",
    cameraMovement: "360° orbit / circular dolly",
    lens: "35mm",
    composition: "centered subject, rotating bg",
    mood: "disorienting, dramatic",
    useCases: ["关键对峙", "揭示时刻", "情绪高潮"],
    prompt: "circular dolly shot orbiting around subject, 360-degree camera move, background motion blur, 35mm lens, dramatic lighting shifting around face, disorienting intensity",
    cinematicParams: { shotScale: 0.35, cameraMotion: 0.7, lighting: 0.6, tone: 0.5, depthOfField: 0.5, aspectRatio: 0.8 },
  },
  {
    id: "action-slow-mo",
    name: "慢动作",
    nameEn: "Slow Motion",
    category: "action",
    shotSize: "medium / close-up",
    cameraAngle: "various",
    cameraMovement: "smooth, slowed",
    lens: "85mm or 50mm",
    composition: "emphasize key action",
    mood: "poetic, heightened",
    useCases: ["关键动作", "情绪爆发", "美学展示"],
    prompt: "slow motion cinematic shot, 120fps aesthetic, smooth fluid movement, 85mm lens, dramatic lighting, particle detail visible, every frame poetic, heightened reality",
    cinematicParams: { shotScale: 0.3, cameraMotion: 0.15, lighting: 0.55, tone: 0.55, depthOfField: 0.7, aspectRatio: 0.8 },
  },
  {
    id: "action-shoulder-rig",
    name: "肩扛跟拍",
    nameEn: "Shoulder Rig Walk",
    category: "action",
    shotSize: "medium / full body",
    cameraAngle: "eye level",
    cameraMovement: "handheld walk-and-talk",
    lens: "35mm",
    composition: "subject centered, slight bob",
    mood: "grounded, documentary",
    useCases: ["对话行走", "调查", "日常跟拍"],
    prompt: "shoulder-mounted walk-and-talk shot, natural handheld bob, subject walking and speaking, 35mm lens, available light, documentary realism, intimate following perspective",
    cinematicParams: { shotScale: 0.5, cameraMotion: 0.6, lighting: 0.4, tone: 0.55, depthOfField: 0.3, aspectRatio: 0.8 },
  },

  // ========================================================================
  // PRODUCT — 商业产品
  // ========================================================================
  {
    id: "product-macro-detail",
    name: "微距细节",
    nameEn: "Macro Detail",
    category: "product",
    shotSize: "extreme close-up / macro",
    cameraAngle: "top-down or 45°",
    cameraMovement: "static or super-slow dolly",
    lens: "100mm macro",
    composition: "centered, texture-focused",
    mood: "premium, tactile",
    useCases: ["珠宝", "美食", "材质展示"],
    prompt: "macro product shot, extreme close-up texture detail, 100mm macro lens f/2.8, razor-thin depth of field, premium lighting, dust-free surface, luxury commercial aesthetic",
    cinematicParams: { shotScale: 0.0, cameraMotion: 0.02, lighting: 0.4, tone: 0.5, depthOfField: 1.0, aspectRatio: 0.7 },
  },
  {
    id: "product-360-spin",
    name: "360旋转展示",
    nameEn: "360 Spin Showcase",
    category: "product",
    shotSize: "medium, centered product",
    cameraAngle: "eye level to slight high",
    cameraMovement: "orbital rotation",
    lens: "50mm",
    composition: "centered on turntable",
    mood: "premium, complete",
    useCases: ["产品展示", "开箱", "电商"],
    prompt: "product 360-degree rotation shot, centered object on clean turntable, smooth orbital camera, 50mm lens, studio lighting, pure white or dark background, premium commercial quality",
    cinematicParams: { shotScale: 0.5, cameraMotion: 0.5, lighting: 0.3, tone: 0.5, depthOfField: 0.4, aspectRatio: 0.7 },
  },
  {
    id: "product-lifestyle",
    name: "生活方式",
    nameEn: "Lifestyle Shot",
    category: "product",
    shotSize: "medium wide",
    cameraAngle: "eye level",
    cameraMovement: "subtle handheld float",
    lens: "35mm",
    composition: "real-life setting",
    mood: "aspirational, authentic",
    useCases: ["服装", "户外装备", "品牌宣传"],
    prompt: "lifestyle product shot, natural environment, aspirational setting, golden hour warm light, 35mm lens, shallow depth of field on product, authentic candid feel, commercial aesthetic",
    cinematicParams: { shotScale: 0.6, cameraMotion: 0.2, lighting: 0.35, tone: 0.75, depthOfField: 0.7, aspectRatio: 0.75 },
  },
  {
    id: "product-hero-light",
    name: "英雄光展示",
    nameEn: "Hero Light Showcase",
    category: "product",
    shotSize: "medium, tight on product",
    cameraAngle: "slightly low for grandeur",
    cameraMovement: "slow push-in",
    lens: "85mm",
    composition: "dramatic spotlighting",
    mood: "heroic, premium, powerful",
    useCases: ["旗舰产品", "新品发布", "品牌大片"],
    prompt: "hero product shot, dramatic spotlighting, slow push-in towards product, 85mm lens, cinematic rim light, floating particles in light beam, premium premium feel, launch film aesthetic",
    cinematicParams: { shotScale: 0.3, cameraMotion: 0.15, lighting: 0.8, tone: 0.45, depthOfField: 0.9, aspectRatio: 0.8 },
  },
  {
    id: "product-food-top",
    name: "美食俯拍",
    nameEn: "Food Top-Down",
    category: "product",
    shotSize: "close-up, overhead",
    cameraAngle: "top-down / flat lay",
    cameraMovement: "static",
    lens: "50mm",
    composition: "flat lay, centered dish",
    mood: "appetizing, styled",
    useCases: ["美食", "菜谱展示", "社交媒体"],
    prompt: "top-down food shot, flat lay composition, styled plating on wooden or marble surface, 50mm lens, soft window light, steam detail visible, mouth-watering appetizing aesthetic",
    cinematicParams: { shotScale: 0.25, cameraMotion: 0.0, lighting: 0.3, tone: 0.7, depthOfField: 0.6, aspectRatio: 0.6 },
  },
  {
    id: "product-splash",
    name: "液体飞溅",
    nameEn: "Liquid Splash",
    category: "product",
    shotSize: "close-up",
    cameraAngle: "eye level or slight side",
    cameraMovement: "static",
    lens: "100mm macro",
    composition: "action frozen in time",
    mood: "dynamic, refreshing",
    useCases: ["饮品", "化妆品", "运动产品"],
    prompt: "liquid splash product shot, water or beverage droplets frozen in mid-air, high-speed capture aesthetic, 100mm macro lens, dramatic dark background, rim light through liquid, refreshing commercial look",
    cinematicParams: { shotScale: 0.15, cameraMotion: 0.0, lighting: 0.7, tone: 0.4, depthOfField: 0.95, aspectRatio: 0.7 },
  },
  {
    id: "product-fashion-cu",
    name: "时尚细节",
    nameEn: "Fashion Detail",
    category: "product",
    shotSize: "close-up, texture/fabric",
    cameraAngle: "eye level or macro",
    cameraMovement: "slow pan across fabric",
    lens: "85mm or 100mm",
    composition: "texture fills frame",
    mood: "luxurious, tactile",
    useCases: ["服装", "面料", "奢侈品"],
    prompt: "fashion texture close-up, silk or leather detail, slow pan across fabric, 85mm lens, soft diffused lighting, tactile luxurious feel, editorial fashion quality, subtle fabric movement",
    cinematicParams: { shotScale: 0.05, cameraMotion: 0.1, lighting: 0.3, tone: 0.55, depthOfField: 0.9, aspectRatio: 0.7 },
  },
  {
    id: "product-unboxing",
    name: "开箱体验",
    nameEn: "Unboxing POV",
    category: "product",
    shotSize: "medium close-up",
    cameraAngle: "POV / over-shoulder",
    cameraMovement: "handheld, natural",
    lens: "28mm",
    composition: "hands in frame",
    mood: "fresh, exciting, first-person",
    useCases: ["开箱", "上手体验", "教程"],
    prompt: "first-person unboxing shot, hands opening premium packaging, natural ambient light, 28mm lens, authentic excitement, product reveal moment, clean composition with hands in frame",
    cinematicParams: { shotScale: 0.35, cameraMotion: 0.4, lighting: 0.4, tone: 0.6, depthOfField: 0.5, aspectRatio: 0.75 },
  },

  // ========================================================================
  // TRANSITION — 转场衔接
  // ========================================================================
  {
    id: "trans-wipe-pass",
    name: "遮挡转场",
    nameEn: "Wipe-by Pass",
    category: "transition",
    shotSize: "medium / wide",
    cameraAngle: "eye level",
    cameraMovement: "dolly or handheld across foreground",
    lens: "35mm",
    composition: "foreground object wipes frame",
    mood: "seamless, creative",
    useCases: ["场景切换", "时间流逝", "创意转场"],
    prompt: "in-camera wipe transition, foreground object or person passes through frame revealing new scene, 35mm lens, seamless matching movement, creative storytelling transition, natural practical effect",
    cinematicParams: { shotScale: 0.5, cameraMotion: 0.6, lighting: 0.5, tone: 0.5, depthOfField: 0.6, aspectRatio: 0.8 },
  },
  {
    id: "trans-match-cut",
    name: "匹配剪辑",
    nameEn: "Match Cut",
    category: "transition",
    shotSize: "close-up / medium",
    cameraAngle: "same as previous shot",
    cameraMovement: "static",
    lens: "50mm",
    composition: "matched shape/motion",
    mood: "clever, symbolic",
    useCases: ["时间跨越", "空间对比", "视觉隐喻"],
    prompt: "match cut transition, shape or motion continues from previous shot, identical composition, 50mm lens, clever visual continuity, symbolic connection between scenes, smooth conceptual transition",
    cinematicParams: { shotScale: 0.3, cameraMotion: 0.0, lighting: 0.5, tone: 0.5, depthOfField: 0.5, aspectRatio: 0.8 },
  },
  {
    id: "trans-rack-defocus",
    name: "景深转场",
    nameEn: "Defocus Rack Transition",
    category: "transition",
    shotSize: "close-up",
    cameraAngle: "eye level",
    cameraMovement: "static",
    lens: "85mm f/1.4",
    composition: "defocus to defocus",
    mood: "dreamy, smooth",
    useCases: ["场景切换", "梦境/回忆", "时间流逝"],
    prompt: "defocus rack transition, shot goes completely out of focus then racks into new scene, 85mm f/1.4, extreme bokeh, dreamy smooth transition, abstract blur, seamless scene change",
    cinematicParams: { shotScale: 0.15, cameraMotion: 0.0, lighting: 0.4, tone: 0.5, depthOfField: 1.0, aspectRatio: 0.8 },
  },
  {
    id: "trans-same-direction",
    name: "同位摇移",
    nameEn: "Same-Direction Pan",
    category: "transition",
    shotSize: "wide",
    cameraAngle: "eye level",
    cameraMovement: "consistent pan speed",
    lens: "35mm",
    composition: "continuous movement direction",
    mood: "flowing, narrative",
    useCases: ["旅程转场", "空间推移", "时间流逝"],
    prompt: "continuous pan transition, camera moves in same direction at same speed across scenes, 35mm lens, flowing narrative movement, seamless spatial progression, Wong Kar-wai step-printing aesthetic",
    cinematicParams: { shotScale: 0.7, cameraMotion: 0.5, lighting: 0.5, tone: 0.55, depthOfField: 0.25, aspectRatio: 0.85 },
  },
  {
    id: "trans-light-bleed",
    name: "光线转场",
    nameEn: "Light Bleed Transition",
    category: "transition",
    shotSize: "close-up / medium",
    cameraAngle: "towards or away from light source",
    cameraMovement: "push into / pull out of light",
    lens: "35mm",
    composition: "overexposed center, dark edges",
    mood: "ethereal, holy",
    useCases: ["回忆开始/结束", "梦境", "幻想"],
    prompt: "light bleed transition, camera pushes into bright light source, overexposure blooms, pulling out reveals new scene, 35mm lens, ethereal radiant glow, dream sequence transition",
    cinematicParams: { shotScale: 0.35, cameraMotion: 0.4, lighting: 0.9, tone: 0.6, depthOfField: 0.4, aspectRatio: 0.8 },
  },
  {
    id: "trans-object-pass",
    name: "物体承接",
    nameEn: "Object Handoff",
    category: "transition",
    shotSize: "close-up on object",
    cameraAngle: "varies",
    cameraMovement: "track object hand-off",
    lens: "50mm",
    composition: "hands passing object",
    mood: "connecting, narrative",
    useCases: ["物品传递", "接力叙事", "多线并进"],
    prompt: "object hand-off transition, item passed from one person to another across scenes, 50mm lens, smooth continuous motion, seamless connection between different locations/times, narrative bridge",
    cinematicParams: { shotScale: 0.2, cameraMotion: 0.35, lighting: 0.45, tone: 0.5, depthOfField: 0.6, aspectRatio: 0.8 },
  },
  {
    id: "trans-reflection",
    name: "镜面反射",
    nameEn: "Reflection Reveal",
    category: "transition",
    shotSize: "close-up / medium",
    cameraAngle: "angled to reflection",
    cameraMovement: "focus pull to reflection",
    lens: "50mm",
    composition: "reflection in glass/water",
    mood: "dreamy, clever",
    useCases: ["内心世界", "回忆闪回", "身份转换"],
    prompt: "reflection transition, scene visible through window or water reflection, focus pulls to reflection revealing new scene, 50mm lens, dreamy poetic transition, mirror magic realism",
    cinematicParams: { shotScale: 0.3, cameraMotion: 0.05, lighting: 0.45, tone: 0.5, depthOfField: 0.8, aspectRatio: 0.8 },
  },
  {
    id: "trans-fade-morph",
    name: "叠化变形",
    nameEn: "Dissolve Morph",
    category: "transition",
    shotSize: "close-up on face/object",
    cameraAngle: "matched angle",
    cameraMovement: "static",
    lens: "85mm",
    composition: "matched between scenes",
    mood: "surreal, flowing",
    useCases: ["时间跳跃", "年龄变化", "蜕变"],
    prompt: "dissolve morph transition, one subject face fades and morphs into another, 85mm lens, static composition, surreal flowing transformation, AI-driven smooth morph, dreamlike time passage",
    cinematicParams: { shotScale: 0.1, cameraMotion: 0.0, lighting: 0.5, tone: 0.5, depthOfField: 0.7, aspectRatio: 0.8 },
  },

  // ========================================================================
  // TENSION — 戏剧张力
  // ========================================================================
  {
    id: "tension-low-angle-power",
    name: "低角压迫",
    nameEn: "Low Angle Power",
    category: "tension",
    shotSize: "medium / full body",
    cameraAngle: "extreme low angle",
    cameraMovement: "slow push-in or static",
    lens: "24mm",
    composition: "subject dwarfs camera",
    mood: "threatening, dominant, oppressive",
    useCases: ["反派登场", "权力压迫", "威胁对峙"],
    prompt: "extreme low angle shot, antagonist towers over camera, 24mm wide distortion, dramatic ceiling or sky background, oppressive presence, harsh shadows, psychological intimidation",
    cinematicParams: { shotScale: 0.55, cameraMotion: 0.1, lighting: 0.85, tone: 0.3, depthOfField: 0.3, aspectRatio: 0.85 },
  },
  {
    id: "tension-symmetrical",
    name: "对称压迫",
    nameEn: "Symmetrical Dread",
    category: "tension",
    shotSize: "wide / extreme wide",
    cameraAngle: "eye level, perfectly centered",
    cameraMovement: "static or slow zoom out",
    lens: "35mm",
    composition: "perfect symmetry",
    mood: "uncanny, oppressive, formal",
    useCases: ["恐怖氛围", "压迫感", "强迫美学"],
    prompt: "perfectly symmetrical wide shot, uncanny Kubrick framing, oppressive stillness, 35mm lens, clinical institutional lighting, deep shadows in corners, unsettling perfection, psychological horror atmosphere",
    cinematicParams: { shotScale: 0.8, cameraMotion: 0.0, lighting: 0.7, tone: 0.25, depthOfField: 0.1, aspectRatio: 0.85 },
  },
  {
    id: "tension-dutch-extreme",
    name: "极端倾斜",
    nameEn: "Extreme Dutch",
    category: "tension",
    shotSize: "medium / close-up",
    cameraAngle: "extreme dutch 45°+",
    cameraMovement: "slight handheld creep",
    lens: "28mm",
    composition: "extreme diagonal tension",
    mood: "paranoid, psychotic, terrifying",
    useCases: ["精神崩溃", "恐怖高潮", "混乱场面"],
    prompt: "extreme dutch angle, 45-degree tilt, disorienting composition, slight handheld creep forward, 28mm lens, harsh green or red tinted lighting, psychological horror, reality breaking",
    cinematicParams: { shotScale: 0.3, cameraMotion: 0.7, lighting: 0.9, tone: 0.15, depthOfField: 0.5, aspectRatio: 0.8 },
  },
  {
    id: "tension-silence-zoom",
    name: "寂静推近",
    nameEn: "Silent Creep Zoom",
    category: "tension",
    shotSize: "wide → close-up",
    cameraAngle: "eye level",
    cameraMovement: "extremely slow dolly zoom",
    lens: "50mm → 85mm",
    composition: "subject slowly fills frame",
    mood: "dread, inevitability, creeping fear",
    useCases: ["恐怖渐近", "真相揭示", "无法逃脱"],
    prompt: "excruciatingly slow dolly zoom, subject gradually fills frame, growing dread, 50mm to 85mm, silence in the air, cold desaturated palette, Hitchcock suspense, unavoidable doom approaching",
    cinematicParams: { shotScale: 0.1, cameraMotion: 0.05, lighting: 0.6, tone: 0.2, depthOfField: 0.6, aspectRatio: 0.8 },
  },
  {
    id: "tension-overhead",
    name: "头顶俯视",
    nameEn: "God's-Eye Overhead",
    category: "tension",
    shotSize: "wide, top-down",
    cameraAngle: "direct overhead",
    cameraMovement: "static or slow rotate",
    lens: "24mm",
    composition: "subjects small in frame",
    mood: "voyeuristic, divine, judgmental",
    useCases: ["犯罪现场", "祭祀场景", "命运转折"],
    prompt: "overhead god's-eye shot, subjects tiny in frame, voyeuristic surveillance perspective, 24mm lens, harsh overhead lighting, geometric floor patterns, cold judgmental composition, crime scene aesthetic",
    cinematicParams: { shotScale: 1.0, cameraMotion: 0.05, lighting: 0.7, tone: 0.3, depthOfField: 0.1, aspectRatio: 0.75 },
  },
  {
    id: "tension-deep-shadow",
    name: "深影恐惧",
    nameEn: "Deep Shadow Dread",
    category: "tension",
    shotSize: "medium / close-up",
    cameraAngle: "eye level",
    cameraMovement: "static",
    lens: "50mm",
    composition: "subject half in shadow",
    mood: "fear, unknown, dual identity",
    useCases: ["恐怖", "犯罪心理", "隐藏真相"],
    prompt: "deep shadow portrait, subject face half-lit half-shadow, dramatic chiaroscuro, 50mm lens, single harsh key light, Caravaggio lighting, fear of the unknown, hidden darkness",
    cinematicParams: { shotScale: 0.2, cameraMotion: 0.0, lighting: 0.95, tone: 0.25, depthOfField: 0.7, aspectRatio: 0.8 },
  },
  {
    id: "tension-tight-space",
    name: "幽闭空间",
    nameEn: "Claustrophobic Tight",
    category: "tension",
    shotSize: "close-up, tight space",
    cameraAngle: "eye level, cramped",
    cameraMovement: "slight tilt, confined",
    lens: "16mm",
    composition: "walls closing in",
    mood: "trapped, suffocating, panicked",
    useCases: ["被困", "密室", "窒息感"],
    prompt: "extreme claustrophobic shot, walls pressing in, wide 16mm lens distortion emphasizing tight space, shallow breathing visible, cold sweat detail, trapped panic, confined space horror",
    cinematicParams: { shotScale: 0.05, cameraMotion: 0.45, lighting: 0.6, tone: 0.2, depthOfField: 0.3, aspectRatio: 0.7 },
  },
  {
    id: "tension-uneasy-stillness",
    name: "不安静止",
    nameEn: "Uneasy Stillness",
    category: "tension",
    shotSize: "wide",
    cameraAngle: "eye level, ridiculously still",
    cameraMovement: "absolutely still locked-off",
    lens: "35mm",
    composition: "empty space dominating",
    mood: "wrongness, uncanny, something's off",
    useCases: ["悬念建立", "恐怖前奏", "异常日常"],
    prompt: "unnervingly still wide shot, locked-off tripod, empty space dominating frame, something subtly wrong, 35mm lens, flat naturalistic lighting, uncanny valley feeling, nothing moves but everything is wrong, David Lynch aesthetic",
    cinematicParams: { shotScale: 0.75, cameraMotion: 0.0, lighting: 0.4, tone: 0.45, depthOfField: 0.15, aspectRatio: 0.85 },
  },
  {
    id: "tension-flicker-horror",
    name: "闪烁恐怖",
    nameEn: "Flicker Horror",
    category: "tension",
    shotSize: "medium / close-up",
    cameraAngle: "eye level",
    cameraMovement: "static",
    lens: "35mm",
    composition: "subject framed by flickering light",
    mood: "terror, supernatural, panic",
    useCases: ["恐怖高潮", "超自然", "灯光故障"],
    prompt: "flickering light horror shot, strobe-like illumination revealing and hiding subject, 35mm lens, harsh on/off lighting, horror aesthetic, supernatural terror, jump-scare building tension, strobe shadow play",
    cinematicParams: { shotScale: 0.4, cameraMotion: 0.0, lighting: 1.0, tone: 0.2, depthOfField: 0.4, aspectRatio: 0.8 },
  },
  {
    id: "tension-rack-fear",
    name: "恐惧变焦",
    nameEn: "Fear Dolly Zoom",
    category: "tension",
    shotSize: "close-up on face",
    cameraAngle: "eye level",
    cameraMovement: "dolly zoom / vertigo effect",
    lens: "50mm zooming wide",
    composition: "face with warping bg",
    mood: "realization, horror, vertigo",
    useCases: ["真相揭示", "精神崩塌", "恐惧降临"],
    prompt: "Hitchcock dolly zoom, face remains same size while background warps, 50mm lens zooming wider while dollying in, vertigo effect, dawning horror on face, cinema classic tension shot",
    cinematicParams: { shotScale: 0.08, cameraMotion: 0.4, lighting: 0.55, tone: 0.3, depthOfField: 0.6, aspectRatio: 0.8 },
  },
]

// ── Quick-lookup map ──────────────────────────────────

export const SHOT_PRESET_MAP = new Map<string, ShotPreset>(
  SHOT_PRESETS.map((p) => [p.id, p]),
)

export function getShotPreset(id: string): ShotPreset | undefined {
  return SHOT_PRESET_MAP.get(id)
}
