// ============================================================================
// Style Library — 100+ 影视级画风库
// ============================================================================
// 数据来源：awesome-seedance (CC BY 4.0) + 影视行业标准画风分类
// 对标：小云雀短剧 Agent 2.0 100+影视画风库
// ============================================================================

export interface StylePreset {
  id: string
  name: string
  nameEn: string
  category: StyleCategory
  visualReference: string // 导演/电影/视觉参考
  promptEnhancement: string // 注入prompt的风格描述
  tags: string[]
  colorPalette?: string // 色调描述
  aspectRatio?: string // 推荐画幅比
}

export type StyleCategory =
  | "cinematic"
  | "advertising"
  | "anime"
  | "drama"
  | "experimental"
  | "documentary"
  | "photography"

export interface StyleCategoryMeta {
  id: StyleCategory
  name: string
  nameEn: string
  icon: string
  description: string
}

// ============================================================================
// Category Definitions
// ============================================================================

export const STYLE_CATEGORIES: StyleCategoryMeta[] = [
  { id: "cinematic", name: "电影感", nameEn: "Cinematic Film", icon: "🎬", description: "好莱坞大片、艺术电影、类型片风格" },
  { id: "advertising", name: "广告商业", nameEn: "Commercial", icon: "📺", description: "品牌广告、产品宣传、MG动画" },
  { id: "anime", name: "动漫动画", nameEn: "Anime & Animation", icon: "🎨", description: "日式动漫、3D动画、艺术动画" },
  { id: "drama", name: "短剧网络剧", nameEn: "Web Drama", icon: "📱", description: "竖屏短剧、微短剧、网剧风格" },
  { id: "experimental", name: "视觉特效", nameEn: "VFX & Experimental", icon: "✨", description: "超现实、视觉特效、实验影像" },
  { id: "documentary", name: "纪实纪录", nameEn: "Documentary", icon: "📹", description: "纪录片、Vlog、真实感拍摄" },
  { id: "photography", name: "摄影风格", nameEn: "Photography", icon: "📷", description: "各类摄影风格与质感" },
]

// ============================================================================
// Style Presets — 30+ 影视级风格（来自 awesome-seedance CC BY 4.0 + 扩展）
// ============================================================================

export const STYLE_PRESETS: StylePreset[] = [
  // ========================================================================
  // CINEMATIC FILM — 电影感
  // ========================================================================
  {
    id: "cinematic-night-rain",
    name: "雨夜赛车",
    nameEn: "Rain Night Racing",
    category: "cinematic",
    visualReference: "Le Mans 66 / Michael Mann",
    promptEnhancement: "cinematic night scene, rain-slicked asphalt, dramatic lighting, high-stakes sports atmosphere, shallow depth of field, anamorphic lens flare, 8K photorealistic",
    tags: ["雨景", "赛车", "夜景", "戏剧性"],
    colorPalette: "深蓝+橙红对比, 高反差",
    aspectRatio: "2.39:1",
  },
  {
    id: "cinematic-epic-desert",
    name: "史诗沙漠",
    nameEn: "Epic Desert",
    category: "cinematic",
    visualReference: "Dune / Denis Villeneuve / IMAX 70mm",
    promptEnhancement: "IMAX 70mm film aesthetic, epic desert landscape, gritty realism, desaturated color palette, massive scale, atmospheric haze, golden hour light, photorealistic cinematic composition",
    tags: ["沙漠", "史诗", "IMAX", "粗粝感"],
    colorPalette: "沙漠金+灰白去饱和",
    aspectRatio: "2.39:1",
  },
  {
    id: "cinematic-wong-kar-wai",
    name: "王家卫港风",
    nameEn: "Wong Kar-wai Style",
    category: "cinematic",
    visualReference: "王家卫 / 花样年华 / 重庆森林",
    promptEnhancement: "90s Hong Kong art cinema aesthetic, retro film grain, yellow-green color tint, step-printing effect, melancholic atmosphere, neon reflections on wet streets, shallow depth of field, intimate framing",
    tags: ["港风", "复古", "霓虹", "忧郁"],
    colorPalette: "黄绿调+霓虹红",
    aspectRatio: "1.85:1",
  },
  {
    id: "cinematic-blade-runner",
    name: "赛博朋克",
    nameEn: "Cyberpunk Noir",
    category: "cinematic",
    visualReference: "Blade Runner 2049 / Roger Deakins",
    promptEnhancement: "cyberpunk aesthetic, neon-lit streets, volumetric fog, rain-soaked urban landscape, holographic advertisements, teal and orange color grade, Roger Deakins lighting style, 8K cinematic",
    tags: ["赛博朋克", "霓虹", "科幻", "雨夜"],
    colorPalette: "青橙对比+霓虹紫",
    aspectRatio: "2.39:1",
  },
  {
    id: "cinematic-jurassic",
    name: "侏罗纪冒险",
    nameEn: "Jurassic Adventure",
    category: "cinematic",
    visualReference: "Jurassic Park / Spielberg",
    promptEnhancement: "Spielberg-style epic adventure, lush jungle environment, dramatic backlight, lens flare, wonder and awe atmosphere, sweeping camera movement, golden sunlight through foliage",
    tags: ["冒险", "丛林", "史诗", "暖光"],
    colorPalette: "丛林绿+金色逆光",
    aspectRatio: "2.39:1",
  },
  {
    id: "cinematic-top-gun",
    name: "壮志凌云",
    nameEn: "Top Gun Aerial",
    category: "cinematic",
    visualReference: "Top Gun: Maverick / aerial cinematography",
    promptEnhancement: "aerial cinematography, fighter jet action, dramatic sky lighting, high-speed motion, intense contrast, sun flare, cockpit POV, crisp 8K detail, military precision",
    tags: ["航空", "军事", "高速", "天空"],
    colorPalette: "蓝天+金属银+橙光",
    aspectRatio: "2.39:1",
  },
  {
    id: "cinematic-indiana-jones",
    name: "印第安纳探险",
    nameEn: "Indiana Jones Adventure",
    category: "cinematic",
    visualReference: "Indiana Jones / ancient temple exploration",
    promptEnhancement: "classic adventure film aesthetic, ancient temple ruins, warm torchlight, dust particles in light beams, mysterious atmosphere, wide establishing shots, golden age Hollywood color grade",
    tags: ["冒险", "古庙", "暖光", "经典"],
    colorPalette: "暖金+棕褐+土色",
    aspectRatio: "2.35:1",
  },
  {
    id: "cinematic-western",
    name: "西部史诗",
    nameEn: "Epic Western",
    category: "cinematic",
    visualReference: "The Searchers / John Ford / Sergio Leone",
    promptEnhancement: "epic western cinematography, vast canyon landscapes, dramatic sky, dust and heat haze, silhouette shots against sunset, wide anamorphic framing, sepia-toned color grade, gritty texture",
    tags: ["西部", "峡谷", "黄昏", "剪影"],
    colorPalette: "橙棕+深褐+暗蓝",
    aspectRatio: "2.39:1",
  },
  {
    id: "cinematic-disaster",
    name: "灾难大片",
    nameEn: "Disaster Epic",
    category: "cinematic",
    visualReference: "Roland Emmerich / tidal wave destruction",
    promptEnhancement: "epic disaster film aesthetic, massive tidal wave, dramatic storm clouds, destruction scale, handheld camera shake, desaturated cold color palette, photorealistic water physics",
    tags: ["灾难", "巨浪", "风暴", "冷调"],
    colorPalette: "灰蓝+暗绿+白浪",
    aspectRatio: "2.39:1",
  },
  {
    id: "cinematic-interstellar",
    name: "星际太空",
    nameEn: "Interstellar Space",
    category: "cinematic",
    visualReference: "Interstellar / Gravity / space cinematography",
    promptEnhancement: "space cinematography, zero-gravity environment, stark contrast between light and void, lens flare from distant stars, IMAX scale, scientific accuracy, emotional isolation, Hans Zimmer-level gravitas",
    tags: ["太空", "科幻", "史诗", "IMAX"],
    colorPalette: "深黑+银白+暗蓝",
    aspectRatio: "2.39:1",
  },

  // ========================================================================
  // ADVERTISING & COMMERCIAL — 广告商业
  // ========================================================================
  {
    id: "ad-fashion",
    name: "时尚大片",
    nameEn: "Fashion Commercial",
    category: "advertising",
    visualReference: "Chanel / Gucci / luxury fashion advertising",
    promptEnhancement: "luxury fashion commercial aesthetic, high-key studio lighting, clean composition, elegant slow motion, metallic and marble textures, sophisticated color palette, premium product focus",
    tags: ["时尚", "奢侈", "高端", "棚拍"],
    colorPalette: "黑白+金属金+大理石灰",
    aspectRatio: "16:9",
  },
  {
    id: "ad-minimalist",
    name: "MUJI极简",
    nameEn: "Minimalist Lifestyle",
    category: "advertising",
    visualReference: "MUJI / Apple / minimalist brand advertising",
    promptEnhancement: "minimalist brand aesthetic, clean white space, natural light, soft shadows, zen composition, warm wood textures, lifestyle product placement, Japanese simplicity philosophy",
    tags: ["极简", "日式", "生活", "自然光"],
    colorPalette: "米白+原木+浅灰",
    aspectRatio: "16:9",
  },
  {
    id: "ad-motion-graphics",
    name: "MG动画",
    nameEn: "Motion Graphics",
    category: "advertising",
    visualReference: "Apple keynote / modern motion graphics",
    promptEnhancement: "3D motion graphics style, clean geometric shapes, smooth easing animations, gradient color transitions, minimalist UI elements, dynamic typography, product showcase with fluid camera movement",
    tags: ["动态图形", "3D", "几何", "科技"],
    colorPalette: "渐变紫蓝+纯白",
    aspectRatio: "16:9",
  },

  // ========================================================================
  // ANIME & ANIMATION — 动漫动画
  // ========================================================================
  {
    id: "anime-shonen",
    name: "热血少年漫",
    nameEn: "Shonen Battle Anime",
    category: "anime",
    visualReference: "Dragon Ball / Naruto / Jujutsu Kaisen",
    promptEnhancement: "shonen anime style, dynamic action poses, speed lines, impact frames, vibrant cel shading, exaggerated perspective, energy aura effects, dramatic camera angles, intense facial expressions",
    tags: ["热血", "战斗", "日漫", "动态"],
    colorPalette: "高饱和红+蓝+黄",
    aspectRatio: "16:9",
  },
  {
    id: "anime-ghibli",
    name: "吉卜力治愈",
    nameEn: "Ghibli Style",
    category: "anime",
    visualReference: "宫崎骏 / 吉卜力工作室",
    promptEnhancement: "Studio Ghibli animation style, hand-drawn aesthetic, soft watercolor backgrounds, warm natural lighting, detailed environmental art, gentle character expressions, nostalgic atmosphere, pastoral landscapes",
    tags: ["治愈", "手绘", "自然", "怀旧"],
    colorPalette: "柔和绿+天蓝+暖黄",
    aspectRatio: "16:9",
  },
  {
    id: "anime-mecha",
    name: "机甲科幻",
    nameEn: "Mecha Anime",
    category: "anime",
    visualReference: "Gundam / Evangelion / mecha genre",
    promptEnhancement: "mecha anime style, detailed mechanical parts, metallic rendering, dramatic explosion effects, cockpit interior shots, scale contrast between robot and environment, cel-shaded 3D hybrid rendering",
    tags: ["机甲", "科幻", "战斗", "金属"],
    colorPalette: "金属灰+警示红+能量蓝",
    aspectRatio: "16:9",
  },
  {
    id: "anime-van-gogh",
    name: "梵高印象派",
    nameEn: "Van Gogh Animation",
    category: "anime",
    visualReference: "梵高 / Loving Vincent / 后印象派",
    promptEnhancement: "Van Gogh post-impressionism animation style, heavy impasto brushstrokes, swirling paint texture, vivid blue-yellow contrast, oil painting aesthetic in motion, expressive color usage, emotional visual language",
    tags: ["艺术", "油画", "印象派", "表现"],
    colorPalette: "深蓝+明黄+翠绿",
    aspectRatio: "16:9",
  },
  {
    id: "anime-stylized-3d",
    name: "风格化3D",
    nameEn: "Stylized 3D Animation",
    category: "anime",
    visualReference: "Spider-Verse / Arcane / Puss in Boots 2",
    promptEnhancement: "stylized 3D animation, non-photorealistic rendering, hand-painted textures, exaggerated proportions, dynamic frame rate changes, painterly lighting, graphic novel aesthetic, bold color palette",
    tags: ["3D", "风格化", "手绘贴图", "美式"],
    colorPalette: "高饱和+漫画网点",
    aspectRatio: "16:9",
  },

  // ========================================================================
  // WEB DRAMA — 短剧网络剧
  // ========================================================================
  {
    id: "drama-vertical-romance",
    name: "竖屏霸总",
    nameEn: "Vertical CEO Drama",
    category: "drama",
    visualReference: "抖音/快手竖屏短剧 / 霸总题材",
    promptEnhancement: "vertical short drama style, portrait 9:16 composition, dramatic emotional close-ups, fast-cut editing rhythm, high-contrast lighting, luxury mansion interiors, intense eye contact, dramatic music video aesthetic",
    tags: ["竖屏", "霸总", "情感", "快节奏"],
    colorPalette: "暖金+深红+暗蓝",
    aspectRatio: "9:16",
  },
  {
    id: "drama-rain-emotional",
    name: "雨夜虐恋",
    nameEn: "Rain Night Melodrama",
    category: "drama",
    visualReference: "微短剧情感戏 / 韩剧风格",
    promptEnhancement: "emotional melodrama style, rain-soaked night scenes, extreme close-up of tears and rain, dramatic slow motion, blue-tinted cold color grade, shallow depth of field, emotional outburst moments, handheld camera intimacy",
    tags: ["情感", "雨景", "特写", "虐心"],
    colorPalette: "冷蓝+苍白+暗灰",
    aspectRatio: "9:16",
  },
  {
    id: "drama-period-qing",
    name: "清宫古装",
    nameEn: "Qing Dynasty Court",
    category: "drama",
    visualReference: "甄嬛传 / 延禧攻略 / 清宫剧",
    promptEnhancement: "Qing dynasty court drama aesthetic, ornate palace interiors, silk and embroidery detail, warm candlelight ambiance, symmetrical composition, muted jewel tone color palette, period-accurate costume design, cinematic widescreen framing",
    tags: ["古装", "宫廷", "清宫", "华美"],
    colorPalette: "朱红+明黄+翠玉绿",
    aspectRatio: "16:9",
  },

  // ========================================================================
  // VFX & EXPERIMENTAL — 视觉特效
  // ========================================================================
  {
    id: "vfx-surreal-megalophobia",
    name: "超现实巨物",
    nameEn: "Surreal Megalophobia",
    category: "experimental",
    visualReference: "Dune sandworm / Arrival / Lovecraftian scale",
    promptEnhancement: "surreal megalophobia aesthetic, impossibly large entities, realistic physics rendering, scale contrast with tiny human figures, atmospheric fog and dust, Hollywood SFX quality, epic visual spectacle",
    tags: ["超现实", "巨物", "恐惧", "史诗"],
    colorPalette: "灰黄+暗棕+迷雾白",
    aspectRatio: "2.39:1",
  },
  {
    id: "vfx-fluid-morph",
    name: "流体变形",
    nameEn: "Fluid Morph Transition",
    category: "experimental",
    visualReference: "AI fluid morph / seamless image transition",
    promptEnhancement: "fluid morph transition, seamless shape transformation, liquid metal aesthetic, organic form flow, surreal metamorphosis, high-frame-rate smooth motion, abstract sculptural evolution",
    tags: ["变形", "流体", "抽象", "转场"],
    colorPalette: "金属银+液态紫+有机绿",
    aspectRatio: "16:9",
  },
  {
    id: "vfx-orbital-collision",
    name: "轨道碰撞",
    nameEn: "Orbital Collision Physics",
    category: "experimental",
    visualReference: "Gravity / Interstellar debris / space physics",
    promptEnhancement: "orbital collision physics simulation, realistic debris field, zero-gravity ragdoll motion, dramatic lighting in vacuum, slow-motion destruction, scientific accuracy, IMAX space cinematography",
    tags: ["太空", "物理", "爆炸", "碎屑"],
    colorPalette: "深空黑+银白碎屑+蓝地球光",
    aspectRatio: "2.39:1",
  },

  // ========================================================================
  // DOCUMENTARY — 纪实纪录
  // ========================================================================
  {
    id: "doc-mockumentary",
    name: "伪纪录片",
    nameEn: "Mockumentary Style",
    category: "documentary",
    visualReference: "The Office / What We Do in the Shadows",
    promptEnhancement: "mockumentary style, handheld camera shake, natural available light, direct-to-camera address, zoom lens aesthetic, slightly desaturated color, documentary realism, intimate character moments, vlog-style authenticity",
    tags: ["手持", "真实", "喜剧", "自然光"],
    colorPalette: "自然色+轻微去饱和",
    aspectRatio: "16:9",
  },
  {
    id: "doc-nature",
    name: "自然纪录",
    nameEn: "Nature Documentary",
    category: "documentary",
    visualReference: "BBC Planet Earth / David Attenborough",
    promptEnhancement: "BBC nature documentary style, macro close-up detail, golden hour wildlife photography, ultra-telephoto compression, slow motion animal behavior, pristine natural lighting, 8K detail, immersive soundscape visual",
    tags: ["自然", "动物", "特写", "金光"],
    colorPalette: "自然绿+金色阳光+深蓝天空",
    aspectRatio: "16:9",
  },

  // ========================================================================
  // PHOTOGRAPHY — 摄影风格
  // ========================================================================
  {
    id: "photo-film-noir",
    name: "黑色电影",
    nameEn: "Film Noir",
    category: "photography",
    visualReference: "黑白胶片 / 40年代好莱坞黑色电影",
    promptEnhancement: "classic film noir aesthetic, high-contrast black and white, venetian blind shadow patterns, dramatic chiaroscuro lighting, smoke-filled rooms, low-angle compositions, hard-boiled detective atmosphere, silver gelatin print texture",
    tags: ["黑白", "高反差", "阴影", "复古"],
    colorPalette: "纯黑白+银灰纹理",
    aspectRatio: "1.85:1",
  },
  {
    id: "photo-kodachrome",
    name: "柯达克罗姆",
    nameEn: "Kodachrome Vintage",
    category: "photography",
    visualReference: "Kodachrome 64 / 70年代彩色胶片",
    promptEnhancement: "Kodachrome 64 film aesthetic, warm saturated colors, slight magenta shift, fine film grain, vintage 1970s color palette, golden hour warmth, nostalgic Americana feel, analog photography texture",
    tags: ["胶片", "复古", "饱和", "怀旧"],
    colorPalette: "暖红+金黄+品红偏移",
    aspectRatio: "3:2",
  },
  {
    id: "photo-cinematic-portrait",
    name: "电影人像",
    nameEn: "Cinematic Portrait",
    category: "photography",
    visualReference: "Annie Leibovitz / cinematic portrait photography",
    promptEnhancement: "cinematic portrait photography, dramatic Rembrandt lighting, shallow f/1.4 depth of field, professional studio setup, hair light separation, editorial magazine quality, emotional eye contact, 85mm portrait lens compression",
    tags: ["人像", "棚拍", "戏剧光", "杂志"],
    colorPalette: "暖肤+深背景+眼神光",
    aspectRatio: "4:5",
  },

  // ========================================================================
  // CINEMATIC FILM — 电影感（扩展 15 项）
  // ========================================================================
  {
    id: "cinematic-horror-found-footage",
    name: "伪纪录恐怖",
    nameEn: "Found Footage Horror",
    category: "cinematic",
    visualReference: "The Blair Witch Project / Paranormal Activity",
    promptEnhancement: "found footage horror aesthetic, handheld shaky camera, night vision green tint, natural available light, grainy low-light sensor noise, first-person POV, authentic amateur documentary feel, genuine fear reactions",
    tags: ["恐怖", "伪纪录片", "手持", "夜视"],
    colorPalette: "暗绿+噪点黑+应急灯",
    aspectRatio: "1.85:1",
  },
  {
    id: "cinematic-psychological-horror",
    name: "心理恐怖",
    nameEn: "Psychological Horror",
    category: "cinematic",
    visualReference: "The Shining / Hereditary / Kubrick",
    promptEnhancement: "psychological horror aesthetic, slow creeping dread, symmetrical Kubrick framing, long unsettling tracking shots, dim atmospheric lighting with deep shadows, oppressive interior spaces, uncanny valley expressions, cold desaturated palette",
    tags: ["恐怖", "心理", "对称", "压抑"],
    colorPalette: "冷灰+暗绿+血红点缀",
    aspectRatio: "1.85:1",
  },
  {
    id: "cinematic-wuxia",
    name: "武侠江湖",
    nameEn: "Wuxia Martial World",
    category: "cinematic",
    visualReference: "卧虎藏龙 / 英雄 / 张艺谋",
    promptEnhancement: "wuxia martial arts cinematic aesthetic, flowing silk robes in wind, bamboo forest setting, slow motion combat choreography, ink wash color palette, ethereal mist and fog, wire-fu gravity-defying movement, poetic composition",
    tags: ["武侠", "竹林", "水墨", "飘逸"],
    colorPalette: "墨绿+素白+朱红点缀",
    aspectRatio: "2.35:1",
  },
  {
    id: "cinematic-ip-man",
    name: "功夫实战",
    nameEn: "Kung Fu Combat",
    category: "cinematic",
    visualReference: "叶问 / 杀破狼 / Donnie Yen",
    promptEnhancement: "grounded kung fu combat aesthetic, realistic close-quarters fighting, dynamic handheld camera, sweat and impact detail, muted concrete and wood textures, fast cut editing rhythm, gritty urban Hong Kong setting",
    tags: ["功夫", "实战", "格斗", "写实"],
    colorPalette: "灰蓝+混凝土+暖黄灯",
    aspectRatio: "16:9",
  },
  {
    id: "cinematic-fantasy-lotr",
    name: "魔幻史诗",
    nameEn: "High Fantasy Epic",
    category: "cinematic",
    visualReference: "The Lord of the Rings / Peter Jackson",
    promptEnhancement: "high fantasy epic aesthetic, sweeping aerial landscape shots, majestic ancient architecture, golden hour backlight through mist, massive scale with tiny figures, warm naturalistic color grade, practical effects realism",
    tags: ["奇幻", "史诗", "魔幻", "宏大"],
    colorPalette: "暖金+翠绿+石灰色",
    aspectRatio: "2.39:1",
  },
  {
    id: "cinematic-hardboiled-detective",
    name: "硬汉侦探",
    nameEn: "Hardboiled Detective",
    category: "cinematic",
    visualReference: "Chinatown / LA Confidential / neo-noir",
    promptEnhancement: "hardboiled detective noir aesthetic, venetian blind shadows across faces, rain-slicked nighttime streets, smoky interrogation rooms, fedora and trench coat silhouette, vintage 1940s cars and neon signs, silver gelatin print texture, cynical world-weary atmosphere",
    tags: ["侦探", "黑色", "复古", "阴影"],
    colorPalette: "深棕+琥珀+霓虹灯",
    aspectRatio: "2.35:1",
  },
  {
    id: "cinematic-war-epic",
    name: "战争史诗",
    nameEn: "War Epic",
    category: "cinematic",
    visualReference: "Saving Private Ryan / 1917 / Dunkirk",
    promptEnhancement: "epic war film aesthetic, desaturated battlefield colors, handheld documentary realism, dirt and debris particle effects, practical explosion and smoke, shallow focus on soldiers\' faces, naturalistic harsh sunlight, visceral immersion",
    tags: ["战争", "史诗", "写实", "手持"],
    colorPalette: "去饱和军绿+泥棕+烟灰",
    aspectRatio: "2.39:1",
  },
  {
    id: "cinematic-period-romance",
    name: "古典爱情",
    nameEn: "Period Romance",
    category: "cinematic",
    visualReference: "Pride and Prejudice / Joe Wright / Atonement",
    promptEnhancement: "period romance aesthetic, soft diffused natural light, English countryside landscapes, Regency or Victorian costume detail, long tracking shots through manor houses, golden hour warm hues, intimate handheld close-ups, Keira Knightley-era cinematography",
    tags: ["爱情", "古典", "英伦", "柔光"],
    colorPalette: "柔金+奶油白+草绿",
    aspectRatio: "2.35:1",
  },
  {
    id: "cinematic-musical",
    name: "歌舞盛宴",
    nameEn: "Movie Musical",
    category: "cinematic",
    visualReference: "La La Land / Moulin Rouge / Chicago",
    promptEnhancement: "movie musical aesthetic, vibrant theatrical colors, elaborate production design, dramatic spotlight lighting, synchronized choreography wide shots, magic hour cityscape backdrops, old Hollywood Technicolor inspiration, dynamic crane camera moves",
    tags: ["歌舞", "绚丽", "舞台", "复古"],
    colorPalette: "品红+宝蓝+金黄",
    aspectRatio: "2.55:1",
  },
  {
    id: "cinematic-heist-thriller",
    name: "高智商劫案",
    nameEn: "Heist Thriller",
    category: "cinematic",
    visualReference: "Ocean\'s Eleven / Heat / Soderbergh",
    promptEnhancement: "heist thriller aesthetic, sleek modern architecture, split-screen and multi-panel composition, cool blue and teal color grade, precision equipment and tech detail, glass and steel urban environments, stylish slow motion, Michael Mann nighttime city aesthetic",
    tags: ["劫案", "犯罪", "科技", "冷峻"],
    colorPalette: "青蓝+钢灰+金色点缀",
    aspectRatio: "2.39:1",
  },
  {
    id: "cinematic-coming-of-age",
    name: "青春成长",
    nameEn: "Coming of Age",
    category: "cinematic",
    visualReference: "Lady Bird / Moonlight / A24 coming-of-age",
    promptEnhancement: "coming-of-age indie film aesthetic, naturalistic available light, warm nostalgic color palette, shallow depth of field intimate portraits, suburban and small-town settings, 35mm film grain texture, handheld intimacy, authentic youth emotion",
    tags: ["青春", "成长", "独立", "怀旧"],
    colorPalette: "暖橘+天蓝+胶片颗粒",
    aspectRatio: "1.85:1",
  },
  {
    id: "cinematic-gothic-horror",
    name: "哥特恐怖",
    nameEn: "Gothic Horror",
    category: "cinematic",
    visualReference: "Crimson Peak / Guillermo del Toro",
    promptEnhancement: "gothic horror aesthetic, decaying Victorian mansions, candlelit interiors, creeping ivy and fog, rich saturated crimson and gold, ornate production design, practical creature effects, dark romantic atmosphere, Guillermo del Toro visual poetry",
    tags: ["哥特", "恐怖", "维多利亚", "浪漫"],
    colorPalette: "深红+暗金+雾灰",
    aspectRatio: "1.85:1",
  },
  {
    id: "cinematic-surreal-dream",
    name: "超现实梦境",
    nameEn: "Surreal Dream Sequence",
    category: "cinematic",
    visualReference: "Inception / The Fall / Tarsem Singh",
    promptEnhancement: "surreal dream sequence aesthetic, impossible architecture and physics, vivid hyper-saturated colors, slow motion and reverse motion effects, practical in-camera tricks, Escher-like spatial paradoxes, theatrical lighting, dreamlike logic",
    tags: ["梦境", "超现实", "鲜艳", "悖论"],
    colorPalette: "超饱和彩虹+深黑",
    aspectRatio: "2.39:1",
  },
  {
    id: "cinematic-silent-film",
    name: "默片时代",
    nameEn: "Silent Film Era",
    category: "cinematic",
    visualReference: "Chaplin / The Artist / silent cinema",
    promptEnhancement: "silent film era aesthetic, black and white high contrast, 16-18 fps slight speed-up motion, iris in/out transitions, intertitle card aesthetic, expressive theatrical acting, vignette frame edges, silver gelatin nitrate film look, Keystone Cops era comedy",
    tags: ["默片", "黑白", "黄金时代", "喜剧"],
    colorPalette: "纯黑白+银盐颗粒",
    aspectRatio: "1.33:1",
  },
  {
    id: "cinematic-french-new-wave",
    name: "法国新浪潮",
    nameEn: "French New Wave",
    category: "cinematic",
    visualReference: "Godard / Truffaut / Breathless",
    promptEnhancement: "French New Wave aesthetic, jump cuts, handheld 16mm camera, natural location shooting, breaking the fourth wall, black and white or muted color, existential cafe scenes, improvised feel, 1960s Paris streets, cinephile references",
    tags: ["新浪潮", "法国", "16mm", "即兴"],
    colorPalette: "黑白+褪色胶片",
    aspectRatio: "1.37:1",
  },

  // ========================================================================
  // ADVERTISING & COMMERCIAL — 广告商业（扩展 12 项）
  // ========================================================================
  {
    id: "ad-sports-action",
    name: "运动极限",
    nameEn: "Sports Action",
    category: "advertising",
    visualReference: "Nike / Red Bull / extreme sports advertising",
    promptEnhancement: "high-energy sports commercial aesthetic, ultra slow motion at 1000fps, sweat and impact particle detail, dramatic stadium lighting, hero athlete silhouette, dynamic Dutch angle shots, motivational atmosphere, product integration in action",
    tags: ["运动", "极限", "慢动作", "英雄"],
    colorPalette: "高饱和红+炭黑+荧光绿",
    aspectRatio: "16:9",
  },
  {
    id: "ad-food-cinematic",
    name: "美食大片",
    nameEn: "Cinematic Food",
    category: "advertising",
    visualReference: "Chef\'s Table / food commercial cinematography",
    promptEnhancement: "cinematic food commercial aesthetic, macro close-up of texture and steam, dramatic side lighting with rim highlights, slow motion ingredient splashes, dark atmospheric backgrounds, golden hour kitchen light, mouthfeel visual poetry",
    tags: ["美食", "特写", "质感", "蒸汽"],
    colorPalette: "深黑+金黄+新鲜红绿",
    aspectRatio: "16:9",
  },
  {
    id: "ad-automotive",
    name: "豪车广告",
    nameEn: "Automotive Commercial",
    category: "advertising",
    visualReference: "BMW / Mercedes / Top Gear cinematography",
    promptEnhancement: "automotive commercial aesthetic, sweeping drone tracking shots, wet asphalt reflections at golden hour, car detail macro shots, dramatic mountain road curves, studio lighting on bodywork, speed blur and motion trails, premium aspirational feel",
    tags: ["汽车", "豪车", "航拍", "速度"],
    colorPalette: "金属银+沥青黑+天际蓝",
    aspectRatio: "16:9",
  },
  {
    id: "ad-tech-product",
    name: "科技产品",
    nameEn: "Tech Product Showcase",
    category: "advertising",
    visualReference: "Apple / Samsung / product launch videos",
    promptEnhancement: "tech product launch aesthetic, 3D product rotation on infinite black, precision close-up of materials and edges, clean white studio lighting, fluid UI animation overlays, minimalist geometric composition, premium material texture, futuristic ambient",
    tags: ["科技", "3D", "极简", "材质"],
    colorPalette: "无限黑+纯白+金属银",
    aspectRatio: "16:9",
  },
  {
    id: "ad-travel-wanderlust",
    name: "旅行大片",
    nameEn: "Travel Wanderlust",
    category: "advertising",
    visualReference: "Airbnb / tourism board / drone travel videos",
    promptEnhancement: "travel wanderlust aesthetic, sweeping drone reveal shots, golden hour and blue hour transitions, solo traveler scale against epic landscapes, aerial top-down beach patterns, local culture candid moments, aspirational freedom feeling",
    tags: ["旅行", "航拍", "自由", "史诗"],
    colorPalette: "碧蓝+绿松+沙金",
    aspectRatio: "16:9",
  },
  {
    id: "ad-cosmetics",
    name: "美妆大片",
    nameEn: "Cosmetics Commercial",
    category: "advertising",
    visualReference: "Dior / Estee Lauder / beauty advertising",
    promptEnhancement: "luxury cosmetics commercial aesthetic, extreme close-up of skin texture and glow, soft ring light catchlight in eyes, product macro with liquid droplet detail, pearlescent and metallic product textures, elegant slow motion, porcelain skin tones",
    tags: ["美妆", "奢华", "肤质", "微距"],
    colorPalette: "玫瑰金+珍珠白+柔粉",
    aspectRatio: "16:9",
  },
  {
    id: "ad-real-estate",
    name: "豪宅大片",
    nameEn: "Luxury Real Estate",
    category: "advertising",
    visualReference: "Sotheby\'s / architectural visualization",
    promptEnhancement: "luxury real estate cinematic aesthetic, smooth gimbal walkthrough, floor-to-ceiling window natural light, twilight exterior with interior glow, marble and hardwood texture detail, infinity pool edge, aspirational lifestyle staging, architectural photography precision",
    tags: ["房产", "豪宅", "建筑", "奢华"],
    colorPalette: "象牙白+大理石+暮光蓝",
    aspectRatio: "16:9",
  },
  {
    id: "ad-kids-education",
    name: "少儿教育",
    nameEn: "Kids Education",
    category: "advertising",
    visualReference: "Duolingo / Khan Academy Kids / children\'s edutainment",
    promptEnhancement: "children\'s educational content aesthetic, bright primary colors, friendly rounded character designs, playful 2D animation, cheerful natural lighting, safe welcoming environments, gentle kinetic typography, wonder and discovery atmosphere",
    tags: ["少儿", "教育", "可爱", "明亮"],
    colorPalette: "纯红+纯黄+纯蓝+纯绿",
    aspectRatio: "16:9",
  },
  {
    id: "ad-medical-health",
    name: "医疗健康",
    nameEn: "Medical Health",
    category: "advertising",
    visualReference: "WHO / healthcare brand advertising",
    promptEnhancement: "medical health commercial aesthetic, clean sterile white environments, soft reassuring lighting, diverse genuine patient and doctor interactions, precise medical equipment detail, calming blue and green accents, trustworthy professional atmosphere",
    tags: ["医疗", "健康", "洁净", "专业"],
    colorPalette: "医白+浅蓝+薄荷绿",
    aspectRatio: "16:9",
  },
  {
    id: "ad-beverage",
    name: "饮品广告",
    nameEn: "Beverage Commercial",
    category: "advertising",
    visualReference: "Coca-Cola / Perrier / craft beer advertising",
    promptEnhancement: "beverage commercial aesthetic, condensation droplets macro, dramatic pour slow motion, ice cube glass clink detail, refreshing splashes, backlit bottle with rim light, summer outdoor lifestyle, thirst-quenching visual satisfaction",
    tags: ["饮品", "清凉", "水珠", "夏日"],
    colorPalette: "冰蓝+气泡白+琥珀棕",
    aspectRatio: "16:9",
  },
  {
    id: "ad-jewelry",
    name: "珠宝大片",
    nameEn: "Jewelry Commercial",
    category: "advertising",
    visualReference: "Cartier / Tiffany / luxury jewelry advertising",
    promptEnhancement: "luxury jewelry commercial aesthetic, extreme macro of gemstone facets and fire, diamond sparkle and prismatic refraction, black velvet background, precise product rotation, soft caress of light on precious metal, editorial fashion integration",
    tags: ["珠宝", "钻石", "奢华", "微距"],
    colorPalette: "丝绒黑+钻石白+宝石彩",
    aspectRatio: "16:9",
  },
  {
    id: "ad-social-media",
    name: "社媒短视频",
    nameEn: "Social Media Short",
    category: "advertising",
    visualReference: "TikTok / Instagram Reels / short-form advertising",
    promptEnhancement: "social media short-form aesthetic, vertical 9:16 composition, bold text overlays, fast jump-cut editing, trending transitions and effects, direct eye contact with camera, phone-native lighting, authentic unpolished feel, hook in first 2 seconds",
    tags: ["社媒", "竖屏", "快节奏", "真实"],
    colorPalette: "高饱和+霓虹+自然光",
    aspectRatio: "9:16",
  },

  // ========================================================================
  // ANIME & ANIMATION — 动漫动画（扩展 10 项）
  // ========================================================================
  {
    id: "anime-horror-junji-ito",
    name: "伊藤润二恐怖",
    nameEn: "Junji Ito Horror",
    category: "anime",
    visualReference: "伊藤润二 / 漩涡 / 富江",
    promptEnhancement: "Junji Ito horror manga aesthetic, hyper-detailed black and white line art, body horror and cosmic dread, intricate cross-hatching, disturbing spiral motifs, realistic grotesque anatomy, psychological terror expressions, stark high-contrast inking",
    tags: ["恐怖", "黑白", "猎奇", "线条"],
    colorPalette: "纯黑白+网点灰",
    aspectRatio: "16:9",
  },
  {
    id: "anime-slice-of-life",
    name: "日常治愈",
    nameEn: "Slice of Life",
    category: "anime",
    visualReference: "K-On / Yuru Camp / 日常系动画",
    promptEnhancement: "iyashikei slice-of-life anime aesthetic, soft pastel color palette, warm afternoon sunlight through windows, detailed background art of everyday spaces, gentle character interactions, cherry blossom and seasonal motifs, relaxing atmosphere, subtle emotional beats",
    tags: ["治愈", "日常", "温暖", "治愈系"],
    colorPalette: "柔粉+天蓝+浅绿+暖黄",
    aspectRatio: "16:9",
  },
  {
    id: "anime-isekai",
    name: "异世界穿越",
    nameEn: "Isekai Fantasy",
    category: "anime",
    visualReference: "Re:Zero / Mushoku Tensei / 异世界题材",
    promptEnhancement: "isekai fantasy anime aesthetic, sprawling medieval fantasy world building, detailed magic circle effects, RPG game UI elements, dramatic boss battle compositions, vibrant elemental spell effects, Japanese light novel art style, adventure party group shots",
    tags: ["异世界", "奇幻", "魔法", "冒险"],
    colorPalette: "翠绿+魔法紫+蓝天+金属",
    aspectRatio: "16:9",
  },
  {
    id: "anime-cyberpunk",
    name: "日系赛博朋克",
    nameEn: "Cyberpunk Anime",
    category: "anime",
    visualReference: "Akira / Ghost in the Shell / 攻壳机动队",
    promptEnhancement: "cyberpunk anime aesthetic, dense futuristic cityscape, holographic kanji advertisements, mecha and cybernetic detail, rain-soaked neon nights, gritty cel animation texture, 80s-90s retro-futurism, philosophical sci-fi atmosphere",
    tags: ["赛博朋克", "未来", "霓虹", "SF"],
    colorPalette: "暗紫+霓虹粉+电路绿",
    aspectRatio: "16:9",
  },
  {
    id: "anime-sports",
    name: "运动热血番",
    nameEn: "Sports Anime",
    category: "anime",
    visualReference: "Haikyuu / Kuroko\'s Basketball / 运动番",
    promptEnhancement: "sports anime aesthetic, dynamic mid-air action freeze frames, speed lines and impact effects, dramatic match point compositions, sweat and determination close-ups, team bonding moments, stadium atmosphere with crowd energy, rotating camera during plays",
    tags: ["运动", "热血", "比赛", "团队"],
    colorPalette: "队服色+场馆光+汗水蓝",
    aspectRatio: "16:9",
  },
  {
    id: "anime-shojo-romance",
    name: "少女恋爱",
    nameEn: "Shojo Romance",
    category: "anime",
    visualReference: "Fruits Basket / Kimi ni Todoke / 少女漫",
    promptEnhancement: "shojo romance anime aesthetic, soft sparkly screen tones, flower petal and bubble backgrounds, large expressive eyes with catchlights, cherry blossom spring settings, blushing and emotional reaction frames, gentle pastel color palette, school rooftop confession scenes",
    tags: ["恋爱", "少女", "樱花", "唯美"],
    colorPalette: "粉红+淡紫+白+樱花色",
    aspectRatio: "16:9",
  },
  {
    id: "anime-samurai",
    name: "武士时代剧",
    nameEn: "Samurai Period Drama",
    category: "anime",
    visualReference: "Samurai Champloo / Rurouni Kenshin / 浪客剑心",
    promptEnhancement: "samurai period anime aesthetic, Edo period historical setting, ink wash brush stroke effects, dramatic sword duel compositions, cherry blossom and falling leaves, traditional Japanese architecture, hip-hop infused aesthetic (Watanabe style), dynamic camera during iaido quick-draw",
    tags: ["武士", "时代剧", "水墨", "剑术"],
    colorPalette: "墨黑+朱红+金+樱花粉",
    aspectRatio: "16:9",
  },
  {
    id: "anime-magical-girl",
    name: "魔法少女",
    nameEn: "Magical Girl",
    category: "anime",
    visualReference: "Sailor Moon / Madoka Magica / 魔法少女",
    promptEnhancement: "magical girl anime aesthetic, elaborate transformation sequence effects, sparkling ribbon and star particle effects, frilly costume detail, crystal and jewel accessories, dramatic silhouette against full moon, friendship power themes, kaleidoscopic background patterns",
    tags: ["魔法少女", "变身", "闪亮", "童话"],
    colorPalette: "粉红+蓝白+星金+虹彩",
    aspectRatio: "16:9",
  },
  {
    id: "anime-stop-motion",
    name: "定格动画",
    nameEn: "Stop Motion",
    category: "anime",
    visualReference: "Laika / Wes Anderson stop motion / 定格动画",
    promptEnhancement: "stop motion animation aesthetic, handcrafted puppet texture visible, miniature set detail, slight frame-to-frame imperfection charm, fabric and clay material warmth, miniature practical lighting, tactile dimensional feel, whimsical character design",
    tags: ["定格", "手工", "木偶", "迷人"],
    colorPalette: "暖布+黏土+微缩灯光",
    aspectRatio: "16:9",
  },
  {
    id: "anime-ink-wash",
    name: "水墨动画",
    nameEn: "Ink Wash Animation",
    category: "anime",
    visualReference: "小蝌蚪找妈妈 / 山水情 / 中国水墨动画",
    promptEnhancement: "Chinese ink wash animation aesthetic, flowing brushstroke motion, xuan paper texture, black ink gradient washes, negative space composition, shanshui landscape painting in motion, calligraphic line quality, poetic Zen atmosphere",
    tags: ["水墨", "中国风", "禅意", "国画"],
    colorPalette: "墨黑+宣纸白+朱砂红",
    aspectRatio: "16:9",
  },

  // ========================================================================
  // WEB DRAMA — 短剧网络剧（扩展 12 项）
  // ========================================================================
  {
    id: "drama-crime-suspense",
    name: "悬疑犯罪",
    nameEn: "Crime Suspense",
    category: "drama",
    visualReference: "隐秘的角落 / 白夜追凶 / 迷雾剧场",
    promptEnhancement: "Chinese crime suspense drama aesthetic, gritty realistic city settings, moody blue-tinted night scenes, tight close-ups of evidence and clues, rain-soaked alleyways, fluorescent interrogation room lighting, slow burn tension building, social realism texture",
    tags: ["悬疑", "犯罪", "冷峻", "社会"],
    colorPalette: "冷蓝+荧光白+暗绿",
    aspectRatio: "16:9",
  },
  {
    id: "drama-family-feud",
    name: "家族恩怨",
    nameEn: "Family Feud",
    category: "drama",
    visualReference: "人世间 / 都挺好 / 家族伦理剧",
    promptEnhancement: "Chinese family drama aesthetic, lived-in domestic interiors, multi-generational dinner table scenes, warm nostalgic lighting mixed with cold tension, subtle facial expressions of resentment, changing seasons marking time passage, realistic household textures, emotional confrontation close-ups",
    tags: ["家庭", "伦理", "代际", "写实"],
    colorPalette: "暖黄+旧木+冷灰",
    aspectRatio: "16:9",
  },
  {
    id: "drama-urban-youth",
    name: "都市青春",
    nameEn: "Urban Youth",
    category: "drama",
    visualReference: "二十不惑 / 欢乐颂 / 都市青春剧",
    promptEnhancement: "Chinese urban youth drama aesthetic, modern city apartment living, neon-lit nighttime cityscape from balcony, trendy fashion and lifestyle, phone screen and social media integration, coworking and cafe hangout settings, dream-chasing ambition, friendship dynamics",
    tags: ["都市", "青春", "职场", "友情"],
    colorPalette: "霓虹+城市灰+暖居灯光",
    aspectRatio: "16:9",
  },
  {
    id: "drama-xianxia",
    name: "古装仙侠",
    nameEn: "Xianxia Fantasy",
    category: "drama",
    visualReference: "苍兰诀 / 花千骨 / 仙侠剧",
    promptEnhancement: "xianxia fantasy drama aesthetic, floating celestial palaces, flowing hanfu robes in wind, magical glowing effects and arrays, peach blossom immortal realms, sword flight and cloud stepping, ethereal beauty filters, romantic tragic atmosphere",
    tags: ["仙侠", "古装", "仙境", "仙气"],
    colorPalette: "雾白+桃粉+仙蓝+金",
    aspectRatio: "16:9",
  },
  {
    id: "drama-campus-romance",
    name: "校园甜宠",
    nameEn: "Campus Romance",
    category: "drama",
    visualReference: "致我们单纯的小美好 / 最好的我们 / 校园剧",
    promptEnhancement: "Chinese campus romance drama aesthetic, bright sunlit classrooms, cherry blossom school pathways, school uniform detail, first love nervous glances, basketball court afternoon scenes, youthful warm filter, nostalgic school bell atmosphere",
    tags: ["校园", "甜宠", "青春", "阳光"],
    colorPalette: "暖阳+校服蓝白+樱花粉",
    aspectRatio: "16:9",
  },
  {
    id: "drama-office-workplace",
    name: "职场商战",
    nameEn: "Office Workplace",
    category: "drama",
    visualReference: "欢乐颂 / 安家 / 职场商战剧",
    promptEnhancement: "Chinese workplace drama aesthetic, sleek modern office interiors, glass-walled conference rooms, late-night overtime desk lamp glow, power dress silhouettes, city skyline from high-rise windows, subtle office politics tension, career ambition visuals",
    tags: ["职场", "商战", "办公室", "野心"],
    colorPalette: "玻璃蓝+水泥灰+深夜灯",
    aspectRatio: "16:9",
  },
  {
    id: "drama-medical",
    name: "医疗剧",
    nameEn: "Medical Drama",
    category: "drama",
    visualReference: "外科风云 / 急诊科医生 / 医疗剧",
    promptEnhancement: "Chinese medical drama aesthetic, sterile hospital corridor tracking shots, dramatic emergency room lighting, surgical team overhead compositions, medical equipment detail, patient-doctor emotional moments, blue-green scrubs and white coats, life-and-death urgency atmosphere",
    tags: ["医疗", "医院", "生命", "专业"],
    colorPalette: "手术绿+无菌白+急救红",
    aspectRatio: "16:9",
  },
  {
    id: "drama-legal",
    name: "律政剧",
    nameEn: "Legal Drama",
    category: "drama",
    visualReference: "精英律师 / Legal High / 律政剧",
    promptEnhancement: "legal drama aesthetic, grand courtroom wide establishing shots, dramatic witness testimony close-ups, leather-bound law library setting, gavel slam slow motion, power suits and formal attire, scales of justice symbolism, verbal duel intensity",
    tags: ["律政", "法庭", "辩论", "正装"],
    colorPalette: "深木色+法官黑+金边",
    aspectRatio: "16:9",
  },
  {
    id: "drama-military",
    name: "军旅题材",
    nameEn: "Military Drama",
    category: "drama",
    visualReference: "士兵突击 / 我是特种兵 / 军旅剧",
    promptEnhancement: "Chinese military drama aesthetic, disciplined training ground wide shots, camouflage and tactical gear detail, brotherhood bonding moments, harsh natural lighting, obstacle course action, barracks daily life, patriotic flag ceremony atmosphere",
    tags: ["军旅", "训练", "战友", "热血"],
    colorPalette: "迷彩绿+土黄+军旗红",
    aspectRatio: "16:9",
  },
  {
    id: "drama-rural",
    name: "乡土叙事",
    nameEn: "Rural Storytelling",
    category: "drama",
    visualReference: "山海情 / 乡村爱情 / 农村题材",
    promptEnhancement: "Chinese rural drama aesthetic, vast agricultural landscapes, weathered but warm village architecture, golden wheat and green rice field textures, rustic daily life details, natural sunlight through dust, genuine unpolished character moments, seasonal farming cycle visuals",
    tags: ["农村", "乡土", "朴实", "自然"],
    colorPalette: "土黄+麦金+天空蓝",
    aspectRatio: "16:9",
  },
  {
    id: "drama-scifi-web",
    name: "科幻短剧",
    nameEn: "Sci-Fi Web Drama",
    category: "drama",
    visualReference: "开端 / 三体 / 科幻微短剧",
    promptEnhancement: "Chinese sci-fi web drama aesthetic, time loop and parallel universe visual motifs, futuristic yet grounded technology, urban sci-fi near-future setting, suspenseful mystery atmosphere, clean modern CGI integration, philosophical sci-fi concepts, time manipulation effects",
    tags: ["科幻", "悬疑", "时间", "近未来"],
    colorPalette: "数字蓝+暗黑+白噪点",
    aspectRatio: "16:9",
  },
  {
    id: "drama-republican-era",
    name: "民国风情",
    nameEn: "Republican Era",
    category: "drama",
    visualReference: "伪装者 / 老九门 / 民国谍战剧",
    promptEnhancement: "Chinese Republican era drama aesthetic, 1930s Shanghai Bund architecture, cheongsam and western suit fusion fashion, vintage street lamps and rickshaws, spy thriller shadow play, art deco interior design, smoky jazz club atmosphere, sepia-toned historical texture",
    tags: ["民国", "谍战", "旗袍", "老上海"],
    colorPalette: "旗袍红+暗绿+旧金+烟灰",
    aspectRatio: "16:9",
  },

  // ========================================================================
  // VFX & EXPERIMENTAL — 视觉特效（扩展 7 项）
  // ========================================================================
  {
    id: "vfx-glitch-art",
    name: "故障艺术",
    nameEn: "Glitch Art",
    category: "experimental",
    visualReference: "datamosh / RGB split / VHS corruption",
    promptEnhancement: "glitch art aesthetic, RGB channel split displacement, digital corruption artifacts, VHS tracking distortion, screen tear and pixel sorting, retro CRT monitor scanlines, data-bending visual language, cyberpunk error aesthetic",
    tags: ["故障", "数字", "VHS", "像素"],
    colorPalette: "RGB分离+品红青偏移",
    aspectRatio: "16:9",
  },
  {
    id: "vfx-particle-dynamics",
    name: "粒子动态",
    nameEn: "Particle Dynamics",
    category: "experimental",
    visualReference: "Houdini particle simulations / VFX breakdowns",
    promptEnhancement: "particle dynamics VFX aesthetic, millions of luminous particles forming shapes, fluid-like smoke trails, sand and dust simulation, spark and ember effects, physically accurate gravity and turbulence, dark atmospheric background, cinematic pyro and fluid sim quality",
    tags: ["粒子", "模拟", "特效", "物理"],
    colorPalette: "暗黑底+发光粒子+火焰橙",
    aspectRatio: "16:9",
  },
  {
    id: "vfx-kaleidoscope",
    name: "万花筒视效",
    nameEn: "Kaleidoscope Effect",
    category: "experimental",
    visualReference: "kaleidoscopic symmetry / fractal visuals",
    promptEnhancement: "kaleidoscope effect aesthetic, perfectly symmetrical radial patterns, fractal mirror reflections, geometric mandala compositions, slow rotation animation, vibrant prismatic colors, hypnotic visual rhythm, psychedelic art influence",
    tags: ["万花筒", "对称", "分形", "迷幻"],
    colorPalette: "全色光谱+万花棱镜",
    aspectRatio: "1:1",
  },
  {
    id: "vfx-ai-hallucination",
    name: "AI幻觉",
    nameEn: "AI Hallucination",
    category: "experimental",
    visualReference: "DeepDream / neural network visualization",
    promptEnhancement: "AI hallucination aesthetic, neural network overfitting patterns, morphing dog-face pareidolia, fractal-like dream logic, latent space interpolation artifacts, surreal image morphing transitions, glitchy data-poisoned visuals, psychedelic AI-generated textures",
    tags: ["AI", "幻觉", "神经网络", "超现实"],
    colorPalette: "迷幻紫+神经网络蓝+异常红",
    aspectRatio: "16:9",
  },
  {
    id: "vfx-time-remap",
    name: "时间重映射",
    nameEn: "Time Remapping",
    category: "experimental",
    visualReference: "speed ramp / bullet time / Matrix",
    promptEnhancement: "time remapping VFX aesthetic, extreme slow motion 1000fps, speed ramp transitions, bullet time 360 camera array, frozen moment with moving camera, temporal displacement effects, reverse motion integration, fluid time manipulation",
    tags: ["时间", "慢动作", "子弹时间", "变速"],
    colorPalette: "冷金属+高速光轨",
    aspectRatio: "2.39:1",
  },
  {
    id: "vfx-datamosh",
    name: "数据损坏",
    nameEn: "Datamosh Effect",
    category: "experimental",
    visualReference: "video compression artifact / I-frame removal",
    promptEnhancement: "datamosh aesthetic, video compression artifact effects, I-frame deletion glitch, pixel block motion trails, digital decay and corruption, raw video data texture, lo-fi compression artifacts, internet-era experimental glitch art",
    tags: ["数据损坏", "压缩", "低保真", "实验"],
    colorPalette: "压缩伪影+像素块+低位深",
    aspectRatio: "16:9",
  },
  {
    id: "vfx-volumetric-light",
    name: "体积光束",
    nameEn: "Volumetric Light Rays",
    category: "experimental",
    visualReference: "God rays / volumetric lighting / atmospheric VFX",
    promptEnhancement: "volumetric light ray VFX aesthetic, dramatic god rays through atmosphere, dusty air particle illumination, cathedral light beam effects, fog and haze volumetric scattering, cinematic shaft of light through windows, atmospheric Tyndall effect, spiritual and epic mood",
    tags: ["光束", "体积光", "丁达尔", "神圣"],
    colorPalette: "金黄光束+暗蓝背景+尘粒",
    aspectRatio: "16:9",
  },

  // ========================================================================
  // DOCUMENTARY — 纪实纪录（扩展 8 项）
  // ========================================================================
  {
    id: "doc-true-crime",
    name: "真实犯罪",
    nameEn: "True Crime",
    category: "documentary",
    visualReference: "Netflix true crime / Making a Murderer",
    promptEnhancement: "true crime documentary aesthetic, evidence board and case file close-ups, moody interrogation room recreations, archival news footage texture, surveillance camera grain, desaturated cold color grade, dramatic reenactment lighting, investigative journalism feel",
    tags: ["犯罪", "调查", "档案", "悬疑"],
    colorPalette: "档案黄+暗蓝+证物灰",
    aspectRatio: "16:9",
  },
  {
    id: "doc-historical",
    name: "历史纪录",
    nameEn: "Historical Documentary",
    category: "documentary",
    visualReference: "Ken Burns / WWII documentaries / 历史频道",
    promptEnhancement: "historical documentary aesthetic, Ken Burns slow zoom on archival photos, sepia-toned period footage, dramatic voiceover visual pacing, map and territory animation, reenactment with period-accurate detail, black and white war photography, historical gravitas",
    tags: ["历史", "档案", "战争", "纪实"],
    colorPalette: "棕褐+老照片黑白+地图色",
    aspectRatio: "16:9",
  },
  {
    id: "doc-travel-vlog",
    name: "旅行Vlog",
    nameEn: "Travel Vlog",
    category: "documentary",
    visualReference: "YouTube travel vloggers / 旅行博主",
    promptEnhancement: "travel vlog aesthetic, direct-to-camera host presentation, stabilized gimbal walk-and-talk, local street food and market detail, drone reveal of destination, candid cultural interactions, first-person experience immersion, warm aspirational wanderlust feel",
    tags: ["旅行", "Vlog", "美食", "文化"],
    colorPalette: "自然色+天蓝+街头鲜艳",
    aspectRatio: "16:9",
  },
  {
    id: "doc-food-culture",
    name: "美食文化",
    nameEn: "Food Culture",
    category: "documentary",
    visualReference: "舌尖上的中国 / Chef\'s Table / food docs",
    promptEnhancement: "food culture documentary aesthetic, macro cooking process detail, steam and sizzle close-ups, artisanal ingredient sourcing landscapes, slow motion plating and serving, warm kitchen atmosphere, hands crafting food, cultural food heritage storytelling",
    tags: ["美食", "文化", "烹饪", "传统"],
    colorPalette: "暖厨光+食材鲜色+蒸汽白",
    aspectRatio: "16:9",
  },
  {
    id: "doc-sports-doc",
    name: "体育纪录",
    nameEn: "Sports Documentary",
    category: "documentary",
    visualReference: "The Last Dance / sports documentaries",
    promptEnhancement: "sports documentary aesthetic, intimate locker room moments, training montage kinetic energy, archival game footage integration, athlete portrait interviews, stadium atmosphere wide shots, sweat and determination detail, underdog triumph narrative",
    tags: ["体育", "热血", "训练", "人生"],
    colorPalette: "球场绿+汗水+冠军金",
    aspectRatio: "16:9",
  },
  {
    id: "doc-music-doc",
    name: "音乐纪录",
    nameEn: "Music Documentary",
    category: "documentary",
    visualReference: "Summer of Soul / music biopics / concert films",
    promptEnhancement: "music documentary aesthetic, live concert energy and crowd, intimate recording studio sessions, instrument close-up performance detail, archival band footage, backstage candid moments, dramatic stage lighting, music-driven visual rhythm",
    tags: ["音乐", "演唱会", "乐队", "创作"],
    colorPalette: "舞台灯光+霓虹+黑白档案",
    aspectRatio: "16:9",
  },
  {
    id: "doc-urban-explore",
    name: "城市探索",
    nameEn: "Urban Exploration",
    category: "documentary",
    visualReference: "urban exploration / street photography docs",
    promptEnhancement: "urban exploration documentary aesthetic, abandoned building decay texture, flashlight beam through darkness, peeling paint and rust detail, wide angle interior reveal, urbex safety gear, post-industrial atmosphere, hidden city history discovery",
    tags: ["探索", "废墟", "城市", "工业"],
    colorPalette: "暗棕+锈红+手电白",
    aspectRatio: "16:9",
  },
  {
    id: "doc-interview",
    name: "人物专访",
    nameEn: "Interview Documentary",
    category: "documentary",
    visualReference: "Errol Morris / interview documentaries",
    promptEnhancement: "interview documentary aesthetic, direct eye contact with Interrotron camera setup, shallow depth of field subject isolation, warm key light with subtle fill, negative space composition for contemplation, b-roll cutaway of subject\'s world, intimate emotional revelation moments",
    tags: ["访谈", "人物", "人生", "特写"],
    colorPalette: "暖肤+深背景+书籍色",
    aspectRatio: "16:9",
  },

  // ========================================================================
  // PHOTOGRAPHY — 摄影风格（扩展 7 项）
  // ========================================================================
  {
    id: "photo-street",
    name: "街头摄影",
    nameEn: "Street Photography",
    category: "photography",
    visualReference: "Henri Cartier-Bresson / street photography",
    promptEnhancement: "street photography aesthetic, decisive moment capture, candid urban life, high contrast black and white, 35mm focal length perspective, geometric composition with human element, light and shadow play on architecture, analog Leica film grain",
    tags: ["街头", "黑白", "纪实", "瞬间"],
    colorPalette: "纯黑白+银盐灰",
    aspectRatio: "3:2",
  },
  {
    id: "photo-landscape",
    name: "风光大片",
    nameEn: "Landscape Photography",
    category: "photography",
    visualReference: "Ansel Adams / National Geographic landscapes",
    promptEnhancement: "landscape photography aesthetic, Ansel Adams zone system tonal range, sweeping vista with foreground interest, dramatic weather and cloud formations, golden hour and blue hour precision, ultra-wide angle 14mm perspective, sharp focus throughout, large format film detail",
    tags: ["风光", "广角", "自然", "宏大"],
    colorPalette: "天际蓝+大地绿+云白",
    aspectRatio: "3:2",
  },
  {
    id: "photo-macro",
    name: "微距世界",
    nameEn: "Macro Photography",
    category: "photography",
    visualReference: "macro insect/plant photography / 1:1 reproduction",
    promptEnhancement: "macro photography aesthetic, 1:1 life-size reproduction ratio, insect compound eye detail, water droplet refraction, flower stamen and pollen texture, razor-thin depth of field, natural diffused lighting, focus stacking clarity, miniature world wonder",
    tags: ["微距", "昆虫", "水滴", "细节"],
    colorPalette: "自然色+彩虹折射",
    aspectRatio: "1:1",
  },
  {
    id: "photo-underwater",
    name: "水下摄影",
    nameEn: "Underwater Photography",
    category: "photography",
    visualReference: "ocean and marine life photography",
    promptEnhancement: "underwater photography aesthetic, natural light caustics through water surface, marine life in crystal clarity, suspended particle backscatter, blue water gradient from shallow to deep, freediving human element, split-level half-above half-below shots, ethereal weightlessness",
    tags: ["水下", "海洋", "潜水", "蓝色"],
    colorPalette: "深蓝+浅青+珊瑚色",
    aspectRatio: "3:2",
  },
  {
    id: "photo-aerial-drone",
    name: "航拍摄影",
    nameEn: "Aerial Drone Photography",
    category: "photography",
    visualReference: "drone / bird\'s eye / aerial photography",
    promptEnhancement: "aerial drone photography aesthetic, top-down bird\'s eye perspective, geometric patterns of landscape and city, long shadow golden hour, revealing scale and order, coastal wave patterns from above, fog layer between mountains, tilt-shift miniature effect",
    tags: ["航拍", "俯瞰", "几何", "尺度"],
    colorPalette: "大地色系+海水蓝+阴影黑",
    aspectRatio: "3:2",
  },
  {
    id: "photo-astrophotography",
    name: "星空摄影",
    nameEn: "Astrophotography",
    category: "photography",
    visualReference: "Milky Way / star trails / night sky long exposure",
    promptEnhancement: "astrophotography aesthetic, Milky Way galaxy core detail, star trail circular long exposure, light-painted foreground landscape, pitch-black night sky clarity, telescope deep space object, aurora borealis color bands, cosmic scale and wonder",
    tags: ["星空", "银河", "长曝光", "宇宙"],
    colorPalette: "深空黑+银河紫+星点白",
    aspectRatio: "3:2",
  },
  {
    id: "photo-double-exposure",
    name: "双重曝光",
    nameEn: "Double Exposure",
    category: "photography",
    visualReference: "in-camera double exposure / surreal composite",
    promptEnhancement: "double exposure photography aesthetic, portrait silhouette filled with landscape, in-camera film multiple exposure, surreal blending of two scenes, dreamlike transparency overlay, human-nature fusion, poetic visual metaphor, analog film experimentation",
    tags: ["双重曝光", "超现实", "融合", "诗意"],
    colorPalette: "人像肤+自然绿+天空",
    aspectRatio: "3:2",
  },


]

// ============================================================================
// Helpers
// ============================================================================

export function getStylesByCategory(category: StyleCategory): StylePreset[] {
  return STYLE_PRESETS.filter((s) => s.category === category)
}

export function getStyleById(id: string): StylePreset | undefined {
  return STYLE_PRESETS.find((s) => s.id === id)
}

export function searchStyles(query: string): StylePreset[] {
  const q = query.toLowerCase()
  return STYLE_PRESETS.filter(
    (s) =>
      s.name.toLowerCase().includes(q) ||
      s.nameEn.toLowerCase().includes(q) ||
      s.tags.some((t) => t.toLowerCase().includes(q)) ||
      s.visualReference.toLowerCase().includes(q),
  )
}

/**
 * 将风格prompt注入到已有的视觉提示词中
 */
export function applyStyleToPrompt(basePrompt: string, styleId: string): string {
  const style = getStyleById(styleId)
  if (!style) return basePrompt
  return `${basePrompt.trim()}, ${style.promptEnhancement}`
}
